using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortalFibrobeton.Models.Class.PeraRaporlar
{
    public class UrunIzlemeModelItem
    {
        public string DOKUM_BARKOD { get; set; }
        public DateTime? PLAN_DOKUM_TARIH { get; set; }
        public string URUN_DURUMU { get; set; }
        public double? BIRIM_KG { get; set; }
        public string HAT { get; set; }
        public string DOKUM_EKIP { get; set; }
        public bool? V_URUN_M2_KULLAN { get; set; }
        public string FRAME_BARKOD { get; set; }
        public DateTime? KUR_SURE_SONU { get; set; }
        public string PS_KAT_ADI { get; set; }
        public bool? DOKUME_BASLANDI { get; set; }
        public bool? GEVSETME_YAPILDI { get; set; }
        public DateTime? GEVSETME_ZAMANI { get; set; }
        public string GEVSETME_YAPAN { get; set; }
        public bool DOKULDU { get; set; }
        public bool? SOKULDU { get; set; }
        public bool? CATLAK_KONTROL_ONAY { get; set; }
        public bool? YUZEY_ISLEM_1_BASLA { get; set; }
        public DateTime? YUZEY_ISLEM_1_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_1_BASLA_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_1_TAMAM { get; set; }
        public DateTime? YUZEY_ISLEM_1_ZAMAN { get; set; }
        public string YUZEY_ISLEM_1_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_2_BASLA { get; set; }
        public DateTime? YUZEY_ISLEM_2_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_2_BASLA_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_2_TAMAM { get; set; }
        public DateTime? YUZEY_ISLEM_2_ZAMAN { get; set; }
        public string YUZEY_ISLEM_2_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_3_BASLA { get; set; }
        public DateTime? YUZEY_ISLEM_3_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_3_BASLA_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_3_TAMAM { get; set; }
        public DateTime? YUZEY_ISLEM_3_ZAMAN { get; set; }
        public string YUZEY_ISLEM_3_YAPAN { get; set; }
        public string YUZEY_ISLEM_4_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_4_TAMAM { get; set; }
        public string YUZEY_ISLEM_5_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_5_TAMAM { get; set; }
        public DateTime? YUZEY_ISLEM_4_ZAMAN { get; set; }
        public DateTime? YUZEY_ISLEM_5_ZAMAN { get; set; }
        public string EK_ISLEM_1_ADI { get; set; }
        public bool? EK_ISLEM_1_TAMAM { get; set; }
        public string EK_ISLEM_1_YAPAN { get; set; }
        public DateTime? EK_ISLEM_1_ZAMAN { get; set; }
        public string EK_ISLEM_2_ADI { get; set; }
        public bool? EK_ISLEM_2_TAMAM { get; set; }
        public string EK_ISLEM_2_YAPAN { get; set; }
        public DateTime? EK_ISLEM_2_ZAMAN { get; set; }
        public string EK_ISLEM_3_ADI { get; set; }
        public bool? EK_ISLEM_3_TAMAM { get; set; }
        public string EK_ISLEM_3_YAPAN { get; set; }
        public DateTime? EK_ISLEM_3_ZAMAN { get; set; }
        public string BLOK_ADI { get; set; }
        public string CEPHE_ADI { get; set; }
        public string CEPHE_KAT_ADI { get; set; }
        public bool? C3D_TARAMA_YAPILDI { get; set; }
        public string C3D_TARAMA_YAPAN { get; set; }
        public DateTime? C3D_TARAMA_ZAMAN { get; set; }
        public bool? YUZEY_ISLEM_4_BASLA { get; set; }
        public DateTime? YUZEY_ISLEM_4_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_4_BASLA_YAPAN { get; set; }
        public bool? YUZEY_ISLEM_5_BASLA { get; set; }
        public string YUZEY_ISLEM_5_BASLA_YAPAN { get; set; }
        public DateTime? YUZEY_ISLEM_5_BASLA_ZAMAN { get; set; }
        public string EK_ISLEM_4_ADI { get; set; }
        public bool? EK_ISLEM_4_TAMAM { get; set; }
        public string EK_ISLEM_4_YAPAN { get; set; }
        public string SANDIK_BARKODU { get; set; }
        public string SEVK_NO { get; set; }
        public bool? AGIRLIK_SORUNLU { get; set; }
        public int? SIPARIS_ID { get; set; }
        public int? SIPARIS_POZ_ID { get; set; }
        public bool? URUN_HOLD { get; set; }
        public string URUN_HOLD_YAPAN { get; set; }
        public DateTime? URUN_HOLD_ZAMAN { get; set; }
        public bool? URUN_KARANTINA { get; set; }
        public string URUN_KARANTINA_YAPAN { get; set; }
        public DateTime? URUN_KARANTINA_ZAMAN { get; set; }
        public bool? URUN_HURDA { get; set; }
        public string URUN_HURDA_YAPAN { get; set; }
        public DateTime? URUN_HURDA_ZAMAN { get; set; }
        public bool? IMHA_BEKLIYOR { get; set; }
        public string IMHA_BEKLIYOR_YAPAN { get; set; }
        public DateTime? IMHA_BEKLIYOR_ZAMAN { get; set; }
        public string FAB_KAB_BEK_YAPAN { get; set; }
        public bool? TAMIR_BAKIM_BEKLIYOR { get; set; }
        public string TAMIR_BAKIM_BEK_YAPAN { get; set; }
        public DateTime? TAMIR_BAKIM_BEK_ZAMAN { get; set; }
        public bool? FABRIKAYA_KABUL_BEKLIYOR { get; set; }
        public DateTime? FAB_KAB_BEK_ZAMAN { get; set; }
        public string POZ_TURU { get; set; }
        public string POZ_NO { get; set; }
        public string POZ_ADI { get; set; }
        public double? BOY { get; set; }
        public double? EN { get; set; }
        public string RENK { get; set; }
        public string MALZEME_YUZEYI { get; set; }
        public string MALZEME_GRUP { get; set; }
        public string MALZEME_CINSI { get; set; }
        public string MALZEME_ADI { get; set; }
        public string POZ_ACIKLAMASI { get; set; }
        public string BIRIM { get; set; }
        public double? BIRIM_M2 { get; set; }
        public double? POZ_TOP_SIP_M2 { get; set; }
        public double? DOKUM_M2 { get; set; }
        public double? POZ_TOP_DOKUM_M2 { get; set; }
        public double? MT { get; set; }
        public double? POZ_TOPLAM_MT { get; set; }
        public double? ONGORULEN_URUN_AGIRLIK { get; set; }
        public double? KESIT_ACILIMI { get; set; }
        public double? KESIT_ACILIM_ARTI { get; set; }
        public double? KESIT_ACILIM_EKSI { get; set; }
        public double? ONCELIK_SIRASI { get; set; }
        public string FRAME_DURUMU { get; set; }
        public double? FRAME_KG { get; set; }
        public bool? YUZ_ISL_VAR { get; set; }
        public bool? GALVENIZE_GITMELI { get; set; }
        public bool? MONTAJSIZ { get; set; }
        public bool? POZ_IPTAL { get; set; }
        public bool? HOLD { get; set; }
        public double? POZ_SIPARIS_MIKTAR { get; set; }
        public double? POZ_REV_EKSI { get; set; }
        public double? POZ_SON_SIPARIS_MIKTAR { get; set; }
        public double? POZ_URETIM_MIKTAR { get; set; }
        public double? POZ_SEVK_MIKTAR { get; set; }
        public double? POZ_MONTAJ_MIKTAR { get; set; }
        public string SON_REV_NO { get; set; }
        public string REPORT_CODE { get; set; }
        public double? ILK_EN { get; set; }
        public double? ILK_BOY { get; set; }
        public double? ILK_BIRIM_M2 { get; set; }
        public string ILK_DOKUM_RENGI { get; set; }
        public string ILK_MALZEME_YUZEYI { get; set; }
        public string ILK_MALZEME_GRUP { get; set; }
        public string ILK_MALZEME_CINSI { get; set; }
        public string ILK_POZ_NO { get; set; }
        public string ILK_MALZEME_ADI { get; set; }
        public string ILK_POZ_TURU { get; set; }
        public double? ILK_HACIM { get; set; }
        public double? BIRIM_HACIM { get; set; }
        public double? POZ_TOPLAM_HACIM { get; set; }
        public string YUZEY_ISLEM_1 { get; set; }
        public string YUZEY_ISLEM_1_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_2 { get; set; }
        public string YUZEY_ISLEM_2_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_3 { get; set; }
        public string YUZEY_ISLEM_3_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_4_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_4 { get; set; }
        public string YUZEY_ISLEM_5 { get; set; }
        public string YUZEY_ISLEM_5_ACIKLAMA { get; set; }
        public bool? MODEL_UYGUNLUK { get; set; }
        public string MODEL_UYG_ONAY_VEREN { get; set; }
        public DateTime? MODEL_UYG_ONAY_TARIH { get; set; }
        public string POZ_BARKOD { get; set; }
        public double? POZ_REV_ARTI { get; set; }
        public double? FRAME_SIPARIS_MIKTAR { get; set; }
        public double? FRAME_KABUL_BEKLE_MIKTAR { get; set; }
        public double? FRAME_GELEN_MIKTAR { get; set; }
        public double? FRAME_GALVENIZLI_MIKTAR { get; set; }
        public double? FRAME_GALVENIZ_BEKLE_MIKTAR { get; set; }
        public double? FRAME_KULLAN_MIKTAR { get; set; }
        public double? FRAME_MUSAIT_MIKTAR { get; set; }
        public double? FRAME_EKSIK_TEMIN { get; set; }
        public string FRAME_TURU { get; set; }
        public double? KALIP_TASARIM_SAYISI { get; set; }
        public double? IS_EMRI_SAYISI { get; set; }
        public string POZ_PLAN_MIKTAR { get; set; }
        public bool? FRAME_DOSYA_YUKLENDI { get; set; }
        public string FRAME_DOSYA_YUKLENDI_YAPAN { get; set; }
        public DateTime? FRAME_DOSYA_YUKLENDI_TARIH { get; set; }
        public int? KALIP_IS_ID { get; set; }
        public bool? AKTIF { get; set; }
        public string DOKUM_IS_EMRI_NO { get; set; }
        public DateTime? PLAN_BASLANGIC_TARIH { get; set; }
        public DateTime? PLAN_BITIS_TARIH { get; set; }
        public double? TOPLAM_DOKULECEK_ADET { get; set; }
        public double? TOPLAM_DOKULEN_ADET { get; set; }
        public double? TOPLAM_KALAN_DOKUM_ADET { get; set; }
        public double? TOPLAM_PLAN_DOK_ADET { get; set; }
        public double? TOPLAM_KALAN_PLAN_ADET { get; set; }
        public DateTime? DOKUM_IS_EMRI_TARIH { get; set; }
        public string DOKUM_IS_EMRINI_VEREN { get; set; }
        public int? KALIP_TASARIM_ID { get; set; }
        public string IS_EMRI_BARKOD { get; set; }
        public DateTime? IS_EMRI_TARIH { get; set; }
        public string IS_EMRI_DURUMU { get; set; }
        public string KALIP_DURUMU { get; set; }
        public DateTime? KALIP_HAZIR_OL_TARIH { get; set; }
        public DateTime? ONG_DOKUM_BASLAMA_TARIH { get; set; }
        public string DOKUM_HOLU { get; set; }
        public double? DOKUM_ORMU_ADET { get; set; }
        public double? TOPLAM_DOKUM_ADET { get; set; }
        public double? KALAN_DOKUM_ADET { get; set; }
        public double? DEPO_ID { get; set; }
        public string DEPO_ADI { get; set; }
        public string DEPO_KONUM { get; set; }
        public string IS_EMRINI_VEREN { get; set; }
        public DateTime? OLUSTURULMA_TARIH { get; set; }
        public bool? KALIP_3D_TARAMA_YAP { get; set; }
        public string KALIP_3D_TARAMA_ONAY_BILGI { get; set; }
        public string KALIPHANELER { get; set; }
        public string KALIPHANE_IMALAT_DURUM { get; set; }
        public int? TADILAT_SAY { get; set; }
        public string KALIPHANE_ISLEM_TURU { get; set; }
        public string KALIPHANE_ISLEM_ADLARI { get; set; }
        public string KALIPHANE_ROTA { get; set; }
        public double? TOPLAM_DOKULECEK_AD { get; set; }
        public double? PLAN_DOKUM_AD { get; set; }
        public double? KALAN_DOKUM_PLAN_AD { get; set; }
        public bool? TAR_MODEL { get; set; }
        public bool? TAR_BETON { get; set; }
        public bool? TAR_KALIP { get; set; }
        public string KALIP_TIPI { get; set; }
        public string PROJE_DURUMU { get; set; }
        public string PROJE_KODU { get; set; }
        public string PROJE_ADI { get; set; }
        public string PROJE_MUDURU { get; set; }
        public string PROJE_YONETICISI { get; set; }
        public string TEKLIF_NO { get; set; }
        public DateTime? SOZLESME_TARIH { get; set; }
        public DateTime? BASLAMA_TARIH { get; set; }
        public DateTime? BITIS_TARIH { get; set; }
        public string PROJE_TURU { get; set; }
        public string PROJE_YERI { get; set; }
        public string PROJE_ADRES { get; set; }
        public string PROJE_ACIKLAMASI { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public double? PROJE_GUN { get; set; }
        public double? PROJE_GERCEK_GUN { get; set; }
        public string PROJE_GERCEK_GUN_LIST { get; set; }
        public bool? URETIM_KONTROL_ONAY { get; set; }
        public bool? SEVK_SAHA_ALINDI { get; set; }
        public bool? K_S_D_SEVK_SAHA_ALINDI { get; set; }
        public bool? Y_I_T_SEVK_SAHA_ALINDI { get; set; }
        public bool? K_S_D_SEVK_ONAY { get; set; }
        public bool? MONTAJ_YAPILDI { get; set; }
        public double? PROJE_SATIS_M2 { get; set; }
        public double? PROJE_SATIS_MIKTAR { get; set; }
        public string MUSTERI_SEVK_PLAN_NO { get; set; }
        public string SANTIYE_SEFI { get; set; }
        public double? SOZLESME_M2 { get; set; }
        public double? SOZLESME_M2_KONTROL_YUZDESI { get; set; }
        public double? WEB_PANEL_YANLIS_SIFRE { get; set; }
        public string WEB_PANEL_KULLANICI_ADI { get; set; }
        public string WEB_PANEL_KULLANICI_SIFRE { get; set; }
        public bool? K_S_D_YUZEY_ISLEMI_YAPILDI { get; set; }
        public DateTime PLAN_OLUSTUR_TARIH { get; set; }
        public string ULKE { get; set; }
        public string IS_DEVIR_ACIKLAMALARI { get; set; }
        public string SOZLESME_NO { get; set; }
        public string BIZDEN_ILGILI { get; set; }
        public string SANDIK_PALET { get; set; }
        public DateTime? V_URUN_M2_SEVK_TARIH { get; set; }
        public string V_URUN_M2_TARIH_ONCE { get; set; }
        public string V_URUN_M2_TARIH_SONRA { get; set; }
        public string MONTAJ_DETAY_PLAN_ACIKLAMA1 { get; set; }
        public string MONTAJ_DETAY_PLAN_ACIKLAMA2 { get; set; }
        public string SANTIYE_SORUMLUSU { get; set; }
        public double? MONTAJ_PLAN_BASLANGIC { get; set; }
        public DateTime? MONTAJ_BASLANMA_TARIH { get; set; }
        public DateTime? MONTAJ_BITIS_TARIH { get; set; }
        public double? MONTAJ_GUN { get; set; }
        public string MASTIK { get; set; }
        public string BOYA { get; set; }
        public double? KUR_SURE_GUN { get; set; }
        public bool? URUN_3D_TARAMA_ZORUNLU { get; set; }
        public bool? KALIP_3D_TARAMA_ZORUNLU { get; set; }
        public bool? MODEL_UYGUNLUK_KONTROL_ZORUNLU { get; set; }
        public bool? KALITE_SON_ONAY { get; set; }
        public bool? POZ_HOLD { get; set; }
        public string OTO_REV_NO { get; set; }
        public DateTime? SIPARIS_BASLANMA_TARIH { get; set; }
        public DateTime? SIPARIS_BITIS_TARIH { get; set; }
        public double? SIPARIS_GUN { get; set; }
        public DateTime? DOKUM_BASLANMA_TARIH { get; set; }
        public DateTime? DOKUM_BITIS_TARIH { get; set; }
        public double? DOKUM_GUN { get; set; }
        public int? POZ_ID { get; set; }
        public string SIPARIS_TURU { get; set; }
        public double? SIPARIS_MIKTAR { get; set; }
        public double? REV_EKSI { get; set; }
        public double? SON_SIPARIS_MIKTAR { get; set; }
        public double? URETIM_MIKTAR { get; set; }
        public double? SEVK_MIKTAR { get; set; }
        public double? MONTAJ_MIKTAR { get; set; }
        public double? TOP_SIP_M2 { get; set; }
        public double? TOPLAM_HACIM { get; set; }
        public double? TOP_DOKUM_M2 { get; set; }
        public double? TOPLAM_MT { get; set; }
        public double? REV_ARTI { get; set; }
        public double? PLANLANAN_MIKTAR { get; set; }
        public double? KALAN_PLAN_MIKTAR { get; set; }
        public string SIPARIS_NO { get; set; }
        public DateTime? SIPARIS_TARIH { get; set; }
        public DateTime? SANDIKLAMA_TARIH { get; set; }
        public string SANDIKLAMA_ACIKLAMASI { get; set; }
        public string PERSONEL_ADI { get; set; }
        public double? SANDIK_TOPLAM_M2 { get; set; }
        public double? SANDIK_TOPLAM_ADET { get; set; }
        public double? SANDIK_TOPLAM_KG { get; set; }
        public string RAF_KONUM { get; set; }
        public string OLUSTURAN { get; set; }
        public DateTime? OLUSTURMA_TARIH { get; set; }
        public string FIS_DURUMU { get; set; }
        public double? YUKSEKLIK { get; set; }
        public double? M3 { get; set; }
        public double? BOS_SANDIK_KG { get; set; }
        public DateTime? PLAN_SEVK_TARIH { get; set; }
        public bool? SEVK_EDILDI { get; set; }
        public int? TALEP_FIS_ID { get; set; }
        public double? SIPARIS_M2 { get; set; }
        public string IRSALIYE_NO { get; set; }
        public string ARAC_PLAKA { get; set; }
        public string SOFOR_ADI { get; set; }
        public string SOFOR_TEL { get; set; }
        public double? SEVK_POZ_MIKTAR { get; set; }
        public double? SEVK_TON { get; set; }
        public string ARAC_TIPI { get; set; }
        public double? ARAC_EN { get; set; }
        public double? ARAC_BOY { get; set; }
        public double? ARAC_MAK_TON { get; set; }
        public string YUKLEYEN { get; set; }
        public DateTime? YUKLEME_ZAMANI { get; set; }
        public string SEVKEDEN_FIRMA { get; set; }
        public int? SEVKEDEN_FIRMA_ID { get; set; }
        public double? SEVK_TUTARI { get; set; }
        public string SEVK_FIS_ACIKLAMA { get; set; }
        public DateTime? ARAC_GIRIS_ZAMAN { get; set; }
        public DateTime? ARAC_CIKIS_ZAMAN { get; set; }
        public double? ILK_TARTIM { get; set; }
        public double? SON_TARTIM { get; set; }
        public DateTime? YUKLEME_BASLAMA_ZAMANI { get; set; }
        public string YUKLEME_SEFI { get; set; }
        public string SANTIYE_KODU { get; set; }
        public int? SANTIYE_ID { get; set; }
        public bool? SANTIYE_SEVK_KABUL { get; set; }
        public string SANTIYE_SEVK_KABUL_EDEN { get; set; }
        public DateTime? SANTIYE_SEVK_KABUL_TARIH { get; set; }
        public string SEVK_KABUL_ACIKLAMA_FIS { get; set; }
        public double? SEVK_PLAN_POZ_MIKTAR { get; set; }
        public double? SEVK_KALAN_POZ_MIKTAR { get; set; }
        public string DORSE_PLAKA_NO { get; set; }
        public string KONTEYNER_NO { get; set; }
        public double? ARAC_YUKLEME_SURE { get; set; }
        public double? ARAC_FABRIKADA_KALMA_SURE { get; set; }
        public double? INDIR_POZ_MIKTAR { get; set; }
        public double? KALAN_INDIR_POZ_MIKTAR { get; set; }
        public double? SEVK_M2 { get; set; }
        public double? MONTAJ_POZ_MIKTAR { get; set; }
        public double? KALAN_MONTAJ_POZ_MIKTAR { get; set; }


    }

}

