//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJANDA
    {
        public long ID { get; set; }
        public string PLAN_KEY { get; set; }
        public Nullable<long> KULLANICI_ID { get; set; }
        public Nullable<System.DateTime> BASLANGIC { get; set; }
        public Nullable<System.DateTime> BITIS { get; set; }
        public string BILGI { get; set; }
        public string KONU { get; set; }
        public Nullable<bool> BASLIK { get; set; }
        public Nullable<long> RENK { get; set; }
        public Nullable<bool> KILIT { get; set; }
        public string FONT { get; set; }
    }
}
