//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketCevaplar
    {
        public int ID { get; set; }
        public Nullable<int> SoruNo { get; set; }
        public Nullable<int> AnketID { get; set; }
        public string AsamaAdi { get; set; }
        public Nullable<double> CevapNo { get; set; }
        public string Soru { get; set; }
        public string AnketiCozen { get; set; }
        public Nullable<System.DateTime> CozumTarihi { get; set; }
        public Nullable<long> ProjeID { get; set; }
    
        public virtual AnketProjeler AnketProjeler { get; set; }
    }
}
