//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSorular
    {
        public long ID { get; set; }
        public Nullable<int> SoruNo { get; set; }
        public Nullable<double> K1 { get; set; }
        public Nullable<double> K2 { get; set; }
        public Nullable<double> K3 { get; set; }
        public Nullable<double> K4 { get; set; }
        public Nullable<double> K5 { get; set; }
        public Nullable<int> AnketID { get; set; }
        public string AsamaAdi { get; set; }
        public string Soru { get; set; }
        public Nullable<double> AsamaKatsayiDegeri { get; set; }
    }
}
