//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSIV_DOKUMAN
    {
        public long ID { get; set; }
        public string BOLUM { get; set; }
        public Nullable<long> VERI_ID { get; set; }
        public string ACIKLAMA { get; set; }
        public string DOSYA_YOLU { get; set; }
        public string KLASOR_YOLU { get; set; }
        public string REF_NO { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUSTURULMA_TARIH { get; set; }
        public string ADI { get; set; }
        public string ARSIV_ADI { get; set; }
        public string SON_GUNCELLEME { get; set; }
        public string KOD { get; set; }
    }
}
