//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYARLAR_GENEL
    {
        public long ID { get; set; }
        public string AYAR_ADI { get; set; }
        public string AYAR_BASLIK { get; set; }
        public string ALAN_TURU { get; set; }
        public Nullable<int> SAYI_ONDALIK { get; set; }
        public string DEGER { get; set; }
    }
}
