//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARKOD_DIZAYN
    {
        public long ID { get; set; }
        public string DOSYA_ADI { get; set; }
        public string DIZAYN_ADI { get; set; }
        public long ETIKET_SAYI { get; set; }
        public string KARAKTER { get; set; }
        public string TURU { get; set; }
    }
}
