//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLUMLER
    {
        public long ID { get; set; }
        public string BOLUM_ADI { get; set; }
        public string BOLUM_KODU { get; set; }
        public string BOLUM_SEFI { get; set; }
        public string BOLUM_SEFI_MAIL { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
