//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPO
    {
        public long ID { get; set; }
        public string DEPO_TURU { get; set; }
        public string DEPO_KODU { get; set; }
        public string DEPO_ADI { get; set; }
        public string YETKILI_ADI { get; set; }
        public string DEPO_ADRESI { get; set; }
        public string DEPO_TELEFON { get; set; }
        public string RAF_KONUM { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
    }
}
