//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOKUM_IS_EMRI
    {
        public long ID { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public string DOKUM_IS_EMRI_NO { get; set; }
        public Nullable<System.DateTime> PLAN_BASLANGIC_TARIH { get; set; }
        public Nullable<System.DateTime> PLAN_BITIS_TARIH { get; set; }
        public Nullable<double> TOPLAM_DOKULECEK_ADET { get; set; }
        public Nullable<double> TOPLAM_DOKULEN_ADET { get; set; }
        public Nullable<double> TOPLAM_KALAN_DOKUM_ADET { get; set; }
        public Nullable<double> TOPLAM_PLAN_DOK_ADET { get; set; }
        public Nullable<double> TOPLAM_KALAN_PLAN_ADET { get; set; }
        public Nullable<System.DateTime> DOKUM_IS_EMRI_TARIH { get; set; }
        public string DOKUM_IS_EMRINI_VEREN { get; set; }
    }
}
