//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOKUM_IS_EMRI_DOKUM
    {
        public long ID { get; set; }
        public string DOKUM_BARKOD { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> DOKUM_IS_ID { get; set; }
        public Nullable<long> DOKUM_POZ_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<System.DateTime> PLAN_DOKUM_TARIH { get; set; }
        public string DOKUM_ACIKLAMASI { get; set; }
        public Nullable<double> BIRIM_KG { get; set; }
        public string HAT { get; set; }
        public string DOKUM_EKIP { get; set; }
        public string URUN_DURUMU { get; set; }
        public Nullable<double> V_URUN_M2 { get; set; }
        public string FRAME_BARKOD { get; set; }
        public Nullable<System.DateTime> KUR_SURE_SONU { get; set; }
        public Nullable<bool> BARKOD_YAZDIRILDI { get; set; }
        public string BARKOD_YAZDIRILDI_YAPAN { get; set; }
        public Nullable<System.DateTime> BARKOD_YAZDIRILDI_TARIH { get; set; }
        public Nullable<bool> DOKUME_BASLANDI { get; set; }
        public string DOKUME_BASLANDI_YAPAN { get; set; }
        public Nullable<System.DateTime> DOKUME_BASLANDI_TARIH { get; set; }
        public Nullable<bool> DOKULDU { get; set; }
        public string DOKULDU_YAPAN { get; set; }
        public Nullable<System.DateTime> DOKULDU_TARIH { get; set; }
        public Nullable<bool> SOKULDU { get; set; }
        public string SOKEN { get; set; }
        public Nullable<System.DateTime> SOKUM_TARIH { get; set; }
        public Nullable<System.DateTime> CATLAK_KONTROL_ONAY_ZAMAN { get; set; }
        public string CATLAK_KONTROL_ONAY_VEREN { get; set; }
        public Nullable<bool> CATLAK_KONTROL_ONAY { get; set; }
        public Nullable<System.DateTime> URETIM_KONTROL_ONAY_ZAMAN { get; set; }
        public string URETIM_KONTROL_ONAY_VEREN { get; set; }
        public Nullable<bool> URETIM_KONTROL_ONAY { get; set; }
        public Nullable<System.DateTime> KALITE_SON_ONAY_ZAMAN { get; set; }
        public string KALITE_SON_ONAY_VEREN { get; set; }
        public Nullable<bool> KALITE_SON_ONAY { get; set; }
        public Nullable<bool> SEVK_SAHA_ALINDI { get; set; }
        public string SEVK_SAHA_ALAN { get; set; }
        public Nullable<System.DateTime> SEVK_SAHA_AL_TARIH { get; set; }
        public Nullable<bool> SEVK_EDILDI { get; set; }
        public string SEVK_YAPAN { get; set; }
        public Nullable<long> SEVK_ID { get; set; }
        public Nullable<long> SEVK_ALT_ID { get; set; }
        public Nullable<bool> INDIRILDI { get; set; }
        public string INDIREN { get; set; }
        public Nullable<System.DateTime> INDIRME_TARIH { get; set; }
        public string SEVK_KABUL_ACIKLAMA { get; set; }
        public Nullable<bool> MONTAJ_YAPILDI { get; set; }
        public string MONTAJ_YAPAN { get; set; }
        public Nullable<System.DateTime> MONTAJ_YAP_TARIH { get; set; }
        public Nullable<long> MONTAJ_FIS_ID { get; set; }
        public Nullable<long> SANDIK_FIS_ID { get; set; }
        public Nullable<long> TASERON_ID { get; set; }
        public string MUSTERI_SEVK_PLAN_NO { get; set; }
        public Nullable<bool> K_S_D_DUZEY_ISL_YAPILDI { get; set; }
        public string K_S_D_DUZEY_ISL_YAPAN { get; set; }
        public Nullable<System.DateTime> K_S_D_DUZEY_ISL_TARIH { get; set; }
        public Nullable<bool> K_S_D_SEVK_SAHA_ALINDI { get; set; }
        public string K_S_D_SEVK_SAHA_ALAN { get; set; }
        public Nullable<System.DateTime> K_S_D_SEVK_SAHA_AL_TARIH { get; set; }
        public Nullable<bool> K_S_D_SEVK_ONAY { get; set; }
        public string K_S_D_SEVK_ONAYLAYAN { get; set; }
        public Nullable<System.DateTime> K_S_D_SEVK_ONAY_TARIH { get; set; }
        public Nullable<bool> Y_I_T_SEVK_SAHA_ALINDI { get; set; }
        public string Y_I_T_SEVK_SAHA_ALAN { get; set; }
        public Nullable<System.DateTime> Y_I_T_SEVK_SAHA_AL_TARIH { get; set; }
        public Nullable<double> BIR_DOKUM_MIKTAR { get; set; }
        public Nullable<double> DOKUM_SIRA { get; set; }
        public Nullable<bool> AYNI_GUN_CIFT_DOKUM { get; set; }
        public Nullable<long> DEPO_ID { get; set; }
        public string RAF_KONUM { get; set; }
        public Nullable<long> SEVK_ONCESI_DEPO_ID { get; set; }
        public Nullable<bool> SAYILDI { get; set; }
        public string SAYILDI_YAPAN { get; set; }
        public Nullable<System.DateTime> SAYILDI_TARIH { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUSTUR_TARIH { get; set; }
        public Nullable<System.DateTime> SEVK_EDILDI_TARIH { get; set; }
        public string DEPO_ADI { get; set; }
        public Nullable<bool> YUZEY_ISLEM_1_TAMAM { get; set; }
        public string YUZEY_ISLEM_1_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_2_TAMAM { get; set; }
        public string YUZEY_ISLEM_2_YAPAN { get; set; }
        public string YUZEY_ISLEM_3_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_3_TAMAM { get; set; }
        public string YUZEY_ISLEM_4_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_4_TAMAM { get; set; }
        public string YUZEY_ISLEM_5_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_5_TAMAM { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_1_ZAMAN { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_2_ZAMAN { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_3_ZAMAN { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_4_ZAMAN { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_5_ZAMAN { get; set; }
        public string EK_ISLEM_1_ADI { get; set; }
        public Nullable<bool> EK_ISLEM_1_TAMAM { get; set; }
        public string EK_ISLEM_1_YAPAN { get; set; }
        public Nullable<System.DateTime> EK_ISLEM_1_ZAMAN { get; set; }
        public string EK_ISLEM_2_ADI { get; set; }
        public Nullable<bool> EK_ISLEM_2_TAMAM { get; set; }
        public string EK_ISLEM_2_YAPAN { get; set; }
        public Nullable<System.DateTime> EK_ISLEM_2_ZAMAN { get; set; }
        public string EK_ISLEM_3_ADI { get; set; }
        public Nullable<bool> EK_ISLEM_3_TAMAM { get; set; }
        public string EK_ISLEM_3_YAPAN { get; set; }
        public Nullable<System.DateTime> EK_ISLEM_3_ZAMAN { get; set; }
        public Nullable<bool> GEVSETME_YAPILDI { get; set; }
        public Nullable<System.DateTime> GEVSETME_ZAMANI { get; set; }
        public string GEVSETME_YAPAN { get; set; }
        public string BLOK_ADI { get; set; }
        public string CEPHE_ADI { get; set; }
        public string CEPHE_KAT_ADI { get; set; }
        public Nullable<bool> C3D_TARAMA_YAPILDI { get; set; }
        public string C3D_TARAMA_YAPAN { get; set; }
        public Nullable<System.DateTime> C3D_TARAMA_ZAMAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_1_BASLA { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_1_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_1_BASLA_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_2_BASLA { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_2_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_2_BASLA_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_3_BASLA { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_3_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_3_BASLA_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_4_BASLA { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_4_BASLA_ZAMAN { get; set; }
        public string YUZEY_ISLEM_4_BASLA_YAPAN { get; set; }
        public Nullable<bool> YUZEY_ISLEM_5_BASLA { get; set; }
        public string YUZEY_ISLEM_5_BASLA_YAPAN { get; set; }
        public Nullable<System.DateTime> YUZEY_ISLEM_5_BASLA_ZAMAN { get; set; }
        public string EK_ISLEM_4_ADI { get; set; }
        public Nullable<bool> EK_ISLEM_4_TAMAM { get; set; }
        public string EK_ISLEM_4_YAPAN { get; set; }
        public string SANDIK_BARKODU { get; set; }
        public string SEVK_NO { get; set; }
        public Nullable<bool> AGIRLIK_SORUNLU { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> SIPARIS_POZ_ID { get; set; }
        public Nullable<bool> URUN_HOLD { get; set; }
        public string URUN_HOLD_YAPAN { get; set; }
        public Nullable<System.DateTime> URUN_HOLD_ZAMAN { get; set; }
        public Nullable<bool> URUN_KARANTINA { get; set; }
        public string URUN_KARANTINA_YAPAN { get; set; }
        public Nullable<System.DateTime> URUN_KARANTINA_ZAMAN { get; set; }
        public Nullable<bool> URUN_HURDA { get; set; }
        public string URUN_HURDA_YAPAN { get; set; }
        public Nullable<System.DateTime> URUN_HURDA_ZAMAN { get; set; }
        public Nullable<bool> IMHA_BEKLIYOR { get; set; }
        public string IMHA_BEKLIYOR_YAPAN { get; set; }
        public Nullable<System.DateTime> IMHA_BEKLIYOR_ZAMAN { get; set; }
        public string FAB_KAB_BEK_YAPAN { get; set; }
        public Nullable<bool> TAMIR_BAKIM_BEKLIYOR { get; set; }
        public string TAMIR_BAKIM_BEK_YAPAN { get; set; }
        public Nullable<System.DateTime> TAMIR_BAKIM_BEK_ZAMAN { get; set; }
        public Nullable<bool> FABRIKAYA_KABUL_BEKLIYOR { get; set; }
        public Nullable<System.DateTime> FAB_KAB_BEK_ZAMAN { get; set; }
        public Nullable<long> SOKUM_UYARI_MAIL_GONDERILDI { get; set; }
    }
}
