//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOVIZ
    {
        public long ID { get; set; }
        public string DOVIZ1 { get; set; }
        public double KUR { get; set; }
        public string ONLINE_ISIM { get; set; }
        public Nullable<long> ALIS_SATIS { get; set; }
        public Nullable<bool> EFEKTIF { get; set; }
    }
}
