//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOVIZ_LOG
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string DOVIZ { get; set; }
        public Nullable<double> ALIS { get; set; }
        public Nullable<double> SATIS { get; set; }
    }
}
