//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRAME_TEDARIKCI_KART
    {
        public long ID { get; set; }
        public string CARI_TURU { get; set; }
        public string CARI_KOD { get; set; }
        public string CARI_ADI { get; set; }
        public string ADRESI { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string VD { get; set; }
        public string VNO { get; set; }
        public string ULKE { get; set; }
        public string ACIKLAMA { get; set; }
        public string TELEFON1 { get; set; }
        public string FAX { get; set; }
        public string WEB { get; set; }
        public string E_MAIL { get; set; }
        public string TELEFON2 { get; set; }
        public string TELEFON3 { get; set; }
        public string MUH_KODU { get; set; }
        public string DURUMU { get; set; }
        public string CARI_GRUP { get; set; }
        public string OLUSTURAN { get; set; }
        public string SON_DUZENLEME { get; set; }
    }
}
