//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRAME_TEDARIK_TADILAT
    {
        public long ID { get; set; }
        public Nullable<long> FRAME_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string TAMIR_BAKIM_ISTEK_YAPAN { get; set; }
        public Nullable<System.DateTime> TAMIR_BAKIM_ISTEK_ZAMAN { get; set; }
        public Nullable<bool> TAMIR_BAKIM_YAPILDI { get; set; }
        public string TAMIR_BAKIM_YAPAN { get; set; }
        public Nullable<System.DateTime> TAMIR_BAKIM_ZAMAN { get; set; }
        public string FRAME_KONTROL_SONUC { get; set; }
        public Nullable<bool> FRAME_KONTROL_ONAY { get; set; }
        public string FRAME_KONTROL_ONAY_VEREN { get; set; }
        public Nullable<System.DateTime> FRAME_KONTROL_ONAY_ZAMAN { get; set; }
        public string UYGUNSUZLUK_NO { get; set; }
    }
}
