//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRAME_TEDARIK
    {
        public long ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> KULLAN_DOKUM_ID { get; set; }
        public string FRAME_BARKOD { get; set; }
        public Nullable<long> CARI_ID { get; set; }
        public string CARI_ADI { get; set; }
        public Nullable<System.DateTime> SIPARIS_TARIH { get; set; }
        public Nullable<System.DateTime> ONG_TESLIM_TARIH { get; set; }
        public string TEDARIK_ACIKLAMASI { get; set; }
        public Nullable<bool> TESLIM_ALINDI { get; set; }
        public Nullable<System.DateTime> TESLIM_ALINDI_TARIH { get; set; }
        public string TESLIM_ALINDI_YAPAN { get; set; }
        public Nullable<bool> GALVENIZDEN_GELDI { get; set; }
        public Nullable<System.DateTime> GALVENIZDEN_GELIS_TARIH { get; set; }
        public string GALVENIZDEN_GELDI_YAPAN { get; set; }
        public Nullable<double> FRAME_BIRIM_KG { get; set; }
        public string DOKUM_TESLIM_ALAN { get; set; }
        public Nullable<bool> DOKUM_TESLIM_ALDI { get; set; }
        public Nullable<System.DateTime> DOKUM_TESLIM_ALDI_TARIH { get; set; }
        public Nullable<bool> BARKOD_YAZDIRILDI { get; set; }
        public Nullable<bool> FRAME_HOLD { get; set; }
        public string FRAME_HOLD_YAPAN { get; set; }
        public Nullable<System.DateTime> FRAME_HOLD_ZAMAN { get; set; }
        public Nullable<bool> FRAME_TAM_BAK_BEKLIYOR { get; set; }
        public string FRAME_TAM_BAK_BEK_YAPAN { get; set; }
        public Nullable<System.DateTime> FRAME_TAM_BAK_BEK_ZAMAN { get; set; }
        public Nullable<bool> FRAME_KARANTINA { get; set; }
        public string FRAME_KARANTINA_YAPAN { get; set; }
        public Nullable<System.DateTime> FRAME_KARANTINA_ZAMAN { get; set; }
        public Nullable<bool> FRAME_HURDA { get; set; }
        public string FRAME_HURDA_YAPAN { get; set; }
        public Nullable<System.DateTime> FRAME_HURDA_ZAMAN { get; set; }
    }
}
