//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIPHANE_KART_ROTA
    {
        public long ID { get; set; }
        public Nullable<long> KALIPHANE_ID { get; set; }
        public string ROTA_ADI { get; set; }
        public Nullable<bool> ORTAK_ROTA { get; set; }
    }
}
