//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_DOKUM_YUZEY
    {
        public long ID { get; set; }
        public Nullable<long> DOKUM_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> SATIR_ID { get; set; }
        public Nullable<bool> BASLADI { get; set; }
        public string BASLADI_YAPAN { get; set; }
        public Nullable<System.DateTime> BASLADI_TARIH { get; set; }
        public Nullable<bool> BITTI { get; set; }
        public string BITTI_YAPAN { get; set; }
        public Nullable<System.DateTime> BITTI_TARIH { get; set; }
    }
}
