//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_KALIPHANE
    {
        public long ID { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<double> KALIPHANE_SIRA { get; set; }
        public string KALIPHANE { get; set; }
        public string KALIPHANE_IMALAT_DURUM { get; set; }
        public string KALIPHANE_ISLEM_TURLERI { get; set; }
        public string KALIPHANE_ISLEM_ADLARI { get; set; }
        public string KALIPHANE_ROTALAR { get; set; }
    }
}
