//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_ROTA
    {
        public long ID { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<double> SIRA { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_TARIH { get; set; }
        public string ROTA_ADI { get; set; }
        public Nullable<System.DateTime> PLANLANAN_TARIH { get; set; }
        public Nullable<bool> TAMAMLANDI { get; set; }
        public Nullable<System.DateTime> TAMAMLANMA_TARIH { get; set; }
        public string TAMAMLANDI_YAPAN { get; set; }
        public Nullable<bool> BASLADI { get; set; }
        public string BASLADI_YAPAN { get; set; }
        public Nullable<System.DateTime> BASLADI_TARIH { get; set; }
        public string KALIPHANE { get; set; }
        public string IMALAT_BARKOD { get; set; }
        public Nullable<long> ROTA_TADILAT_SAY { get; set; }
        public Nullable<long> ISLEM_ID { get; set; }
        public string KALIPHANE_ISLEM_TURU { get; set; }
        public string KALIPHANE_ISLEM_ADI { get; set; }
        public Nullable<double> ONG_SURE { get; set; }
        public Nullable<double> ROTA_SURE { get; set; }
        public Nullable<double> FARK_SURE { get; set; }
    }
}
