//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_TASARIM_POZ
    {
        public long ID { get; set; }
        public Nullable<double> KALIP_TASARIM_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<bool> ANA_POZ { get; set; }
        public Nullable<double> TASARIM_SIRA { get; set; }
    }
}
