//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_NP
    {
        public long ID { get; set; }
        public Nullable<double> KALIP_TASARIM_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string IS_EMRI_BARKOD { get; set; }
        public Nullable<System.DateTime> IS_EMRI_TARIH { get; set; }
        public string IS_EMRI_DURUMU { get; set; }
        public string KALIP_DURUMU { get; set; }
        public Nullable<System.DateTime> KALIP_HAZIR_OL_TARIH { get; set; }
        public Nullable<System.DateTime> ONG_DOKUM_BASLAMA_TARIH { get; set; }
        public string DOKUM_HOLU { get; set; }
        public Nullable<double> DOKUM_ORMU_ADET { get; set; }
        public Nullable<double> TOPLAM_DOKUM_ADET { get; set; }
        public Nullable<double> KALAN_DOKUM_ADET { get; set; }
        public Nullable<double> DEPO_ID { get; set; }
        public string DEPO_ADI { get; set; }
        public string DEPO_KONUM { get; set; }
        public string IS_EMRINI_VEREN { get; set; }
        public Nullable<System.DateTime> OLUSTURULMA_TARIH { get; set; }
        public Nullable<bool> KALIP_3D_TARAMA_YAP { get; set; }
        public string KALIP_3D_TARAMA_ONAY_BILGI { get; set; }
        public string KALIPHANELER { get; set; }
        public string KALIPHANE_IMALAT_DURUM { get; set; }
        public Nullable<long> TADILAT_SAY { get; set; }
        public string KALIPHANE_ISLEM_TURU { get; set; }
        public string KALIPHANE_ISLEM_ADLARI { get; set; }
        public string KALIPHANE_ROTA { get; set; }
        public Nullable<double> TOPLAM_DOKULECEK_AD { get; set; }
        public Nullable<double> PLAN_DOKUM_AD { get; set; }
        public Nullable<double> KALAN_DOKUM_PLAN_AD { get; set; }
        public Nullable<bool> TAR_MODEL { get; set; }
        public Nullable<bool> TAR_BETON { get; set; }
        public Nullable<bool> TAR_KALIP { get; set; }
        public string KALIP_TIPI { get; set; }
        public Nullable<System.DateTime> KALIP_HAZIR_ONAY_TARIH { get; set; }
        public Nullable<System.DateTime> ONG_KALIP_BASLANGIC_TARIH { get; set; }
        public string KALIP_IS_EMRI_ACIKLAMASI { get; set; }
    }
}
