//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_POZ
    {
        public long ID { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public string POZ_NO { get; set; }
        public Nullable<long> DOKULECEK_MIKTAR { get; set; }
        public Nullable<bool> ANA_POZ { get; set; }
        public Nullable<long> SIRA { get; set; }
        public Nullable<double> TOP_DOKULECEK_M2 { get; set; }
        public Nullable<long> KIE_URETIM_MIKTAR { get; set; }
        public Nullable<long> KIE_SEVK_MIKTAR { get; set; }
        public Nullable<long> KIE_KAL_SEVK_MIKTAR { get; set; }
        public Nullable<long> KIE_KAL_DOK_MIKTAR { get; set; }
        public string POZ_BARKOD { get; set; }
    }
}
