//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_TASARIM_FORM
    {
        public long ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string KALIP_ADI { get; set; }
        public string ANA_POZ_NO { get; set; }
        public string DOKUM_SEKLI { get; set; }
        public Nullable<double> KALIP_BOY { get; set; }
        public Nullable<double> KALIP_EN { get; set; }
        public Nullable<double> KALIP_M2 { get; set; }
        public string KALIP_TASARIM_ACIKLAMASI { get; set; }
        public Nullable<bool> KY_DUZ { get; set; }
        public Nullable<bool> KY_MKT_TEKSTURLU { get; set; }
        public Nullable<bool> KY_POLY_TEKSTURLU { get; set; }
        public Nullable<bool> KY_KAU_TEKSTURLU { get; set; }
        public Nullable<bool> KY_DIGER { get; set; }
        public string KY_DIGER_ADI { get; set; }
        public string TASARIM_NO { get; set; }
    }
}
