//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_KALITE_KONTROL
    {
        public long ID { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<System.DateTime> KONTROL_ZAMANI { get; set; }
        public string KONTROL_EDEN { get; set; }
        public string KALITE_KONTROL_TURU { get; set; }
        public string KALITE_KONTROL_ACIKLAMASI { get; set; }
        public string SONUC { get; set; }
        public Nullable<long> EK_ID { get; set; }
        public string EK_TURU { get; set; }
    }
}
