//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_KALIP_OLUSTUR
    {
        public long ID { get; set; }
        public string KALIPHANE { get; set; }
        public string ISLEM_TURU { get; set; }
        public string ISLEM { get; set; }
        public Nullable<double> M2 { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public string KALIPHANE_DURUM { get; set; }
    }
}
