//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_DOKUM
    {
        public long ID { get; set; }
        public string DOKUM_BARKOD { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> KALIP_POZ_ID { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string POZ_NO { get; set; }
        public Nullable<System.DateTime> DOKUM_TARIH { get; set; }
        public Nullable<System.DateTime> KUR_SURE_SONU { get; set; }
        public string DOKUM_ACIKLAMASI { get; set; }
        public Nullable<bool> DOKULDU { get; set; }
        public string DOKULDU_YAPAN { get; set; }
        public Nullable<System.DateTime> DOKULDU_TARIH { get; set; }
        public string FRAME_BARKOD { get; set; }
        public string KALIP_BARKOD { get; set; }
        public Nullable<bool> YUZEY_TAMAM { get; set; }
        public string YUZEY_TAMAM_YAPAN { get; set; }
        public Nullable<System.DateTime> YUZEY_TAMAM_TARIH { get; set; }
        public Nullable<bool> SEVKE_HAZIR { get; set; }
        public string SEVKE_HAZIR_YAPAN { get; set; }
        public Nullable<System.DateTime> SEVKE_HAZIR_TARIH { get; set; }
        public Nullable<bool> SEVK_EDILDI { get; set; }
        public string SEVK_YAPAN { get; set; }
        public Nullable<System.DateTime> SEVK_TARIH { get; set; }
        public Nullable<long> SEVK_ID { get; set; }
        public Nullable<double> BIRIM_KG { get; set; }
        public string RAF_KONUM { get; set; }
        public string SEVK_NO { get; set; }
        public Nullable<bool> SEVK_SAHA_ALINDI { get; set; }
        public string SEVK_SAHA_ALAN { get; set; }
        public Nullable<System.DateTime> SEVK_SAHA_AL_TARIH { get; set; }
        public Nullable<bool> K_S_D_SEVK_SAHA_ALINDI { get; set; }
        public string K_S_D_SEVK_SAHA_ALAN { get; set; }
        public Nullable<System.DateTime> K_S_D_SEVK_SAHA_AL_TARIH { get; set; }
        public Nullable<bool> K_S_D_SEVK_ONAY { get; set; }
        public string K_S_D_SEVK_ONAYLAYAN { get; set; }
        public Nullable<System.DateTime> K_S_D_SEVK_ONAY_TARIH { get; set; }
        public Nullable<bool> SOKULDU { get; set; }
        public string SOKEN { get; set; }
        public Nullable<System.DateTime> SOKUM_TARIH { get; set; }
        public string HAT { get; set; }
        public Nullable<bool> DOKUME_BASLANDI { get; set; }
        public string DOKUME_BASLANDI_YAPAN { get; set; }
        public Nullable<System.DateTime> DOKUME_BASLANDI_TARIH { get; set; }
        public Nullable<bool> K_S_D_DUZEY_ISL_YAPILDI { get; set; }
        public string K_S_D_DUZEY_ISL_YAPAN { get; set; }
        public Nullable<System.DateTime> K_S_D_DUZEY_ISL_TARIH { get; set; }
        public Nullable<long> BIR_DOKUM_MIKTAR { get; set; }
        public Nullable<long> SEVK_ALT_ID { get; set; }
        public Nullable<bool> AYNI_GUN_CIFT_DOKUM { get; set; }
        public Nullable<long> TOP_SEVK_MIKTAR { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUSTUR_TARIH { get; set; }
        public Nullable<long> DOKUM_SIRA { get; set; }
        public Nullable<System.DateTime> FRAME_EKLEME_ZAMANI { get; set; }
        public string SANTIYE_KODU { get; set; }
        public Nullable<long> SANTIYE_ID { get; set; }
        public Nullable<bool> INDIRILDI { get; set; }
        public string INDIREN { get; set; }
        public Nullable<System.DateTime> INDIRME_TARIH { get; set; }
        public Nullable<bool> MONTAJ_YAPILDI { get; set; }
        public string MONTAJ_YAPAN { get; set; }
        public Nullable<System.DateTime> MONTAJ_YAP_TARIH { get; set; }
        public string TASERON_ADI { get; set; }
        public Nullable<long> TASERON_ID { get; set; }
        public string SEVK_KABUL_ACIKLAMA { get; set; }
        public Nullable<bool> Y_I_T_SEVK_SAHA_ALINDI { get; set; }
        public string Y_I_T_SEVK_SAHA_ALAN { get; set; }
        public Nullable<System.DateTime> Y_I_T_SEVK_SAHA_AL_TARIH { get; set; }
        public Nullable<bool> BARKOD_YAZDIRILDI { get; set; }
        public string BARKOD_YAZDIRILDI_YAPAN { get; set; }
        public Nullable<System.DateTime> BARKOD_YAZDIRILDI_TARIH { get; set; }
        public Nullable<bool> SAYILDI { get; set; }
        public string SAYILDI_YAPAN { get; set; }
        public Nullable<System.DateTime> SAYILDI_TARIH { get; set; }
        public Nullable<long> DEPO_ID { get; set; }
        public string DEPO_ADI { get; set; }
        public Nullable<long> SEVK_ONCESI_DEPO_ID { get; set; }
        public string URUN_DURUMU { get; set; }
        public Nullable<long> SANDIK_FIS_ID { get; set; }
        public Nullable<double> V_URUN_M2 { get; set; }
        public string MUSTERI_SEVK_PLAN_NO { get; set; }
        public Nullable<System.DateTime> KALITE_SON_ONAY_ZAMAN { get; set; }
        public string KALITE_SON_ONAY_VEREN { get; set; }
        public Nullable<bool> KALITE_SON_ONAY { get; set; }
        public Nullable<System.DateTime> CATLAK_KONTROL_ONAY_ZAMAN { get; set; }
        public string CATLAK_KONTROL_ONAY_VEREN { get; set; }
        public Nullable<bool> CATLAK_KONTROL_ONAY { get; set; }
        public Nullable<System.DateTime> URETIM_KONTROL_ONAY_ZAMAN { get; set; }
        public string URETIM_KONTROL_ONAY_VEREN { get; set; }
        public Nullable<bool> URETIM_KONTROL_ONAY { get; set; }
        public string DOKUM_EKIP { get; set; }
    }
}
