//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_FRAME_TEDARIK
    {
        public long ID { get; set; }
        public string FRAME_BARKOD { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> KALIP_POZ_ID { get; set; }
        public Nullable<long> KALIP_IS_ID { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> CARI_ID { get; set; }
        public string CARI_ADI { get; set; }
        public string POZ_NO { get; set; }
        public Nullable<System.DateTime> TAS_SIPARIS_TARIH { get; set; }
        public Nullable<System.DateTime> TESLIM_TARIH { get; set; }
        public string TEDARIK_ACIKLAMASI { get; set; }
        public Nullable<bool> TESLIM_ALINDI { get; set; }
        public Nullable<double> BIRIM_KG { get; set; }
        public Nullable<bool> BARKOD_YAZDIRILDI { get; set; }
        public string TESLIM_ALINDI_YAPAN { get; set; }
        public string GALVENIZ_TAMAM_YAPAN { get; set; }
        public Nullable<System.DateTime> TESLIM_ALINDI_TARIH { get; set; }
        public Nullable<System.DateTime> GALVENIZ_TARIH { get; set; }
        public Nullable<bool> GALVENIZ { get; set; }
        public string IS_EMRI_BARKOD { get; set; }
        public string POZ_BARKOD { get; set; }
        public string DOKUM_TESLIM_ALAN { get; set; }
        public Nullable<bool> DOKUM_TESLIM_ALDI { get; set; }
        public Nullable<System.DateTime> DOKUM_TESLIM_ALDI_TARIH { get; set; }
        public string HOL { get; set; }
    }
}
