//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KALIP_IS_EMRI_DOKUM_LOG
    {
        public long ID { get; set; }
        public Nullable<long> DOKUM_ID { get; set; }
        public string TURU { get; set; }
        public string ALAN { get; set; }
        public string ONCEKI_BILGI { get; set; }
        public string YENI_BILGI { get; set; }
        public string DEGISTIREN { get; set; }
        public Nullable<System.DateTime> DEGISIM_TARIH { get; set; }
    }
}
