//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI_KART_AYARLARI
    {
        public long ID { get; set; }
        public Nullable<long> KULLANICI_ID { get; set; }
        public string FORM { get; set; }
        public string GORUNUM_DATA { get; set; }
        public Nullable<int> GORUNUM_YUKSEKLIK { get; set; }
        public Nullable<int> GORUNUM_SATIR { get; set; }
        public Nullable<int> GORUNUM_SUTUN { get; set; }
        public string GORUNUM_BASLIK_FONT { get; set; }
        public string GORUNUM_ALAN_FONT { get; set; }
        public Nullable<int> ISLEM_BUTON_GENISLIK { get; set; }
        public Nullable<int> ISLEM_BUTON_YUKSEKLIK { get; set; }
        public Nullable<int> ISLEM_BUTON_FONT_SIZE { get; set; }
    }
}
