//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI_NP
    {
        public long ID { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string SIFRE { get; set; }
        public string ADI_SOYADI { get; set; }
        public Nullable<bool> YONETICI { get; set; }
        public string UNVAN { get; set; }
        public string BOLUM { get; set; }
        public string HAT { get; set; }
        public string DOKUM_HOLU { get; set; }
        public string PROJE_YETKI { get; set; }
        public string DEPO_YETKI { get; set; }
        public string BARKOD_YAZDIR_BAT_SEC { get; set; }
        public string ARSIV_YOL_SEC { get; set; }
        public byte[] KULLANICI_RESIM { get; set; }
        public Nullable<long> PERSONEL_ID { get; set; }
        public Nullable<long> AJANDA_ZAMAN_ARALIK { get; set; }
        public Nullable<long> AJANDA_GORUNEN_BASLANGIC { get; set; }
        public Nullable<long> AJANDA_GORUNEN_BITIS { get; set; }
        public Nullable<long> AJANDA_AKTIF_BASLANGIC { get; set; }
        public Nullable<long> AJANDA_AKTIF_BITIS { get; set; }
        public Nullable<long> AJANDA_GUN_SAYI { get; set; }
        public Nullable<long> AJANDA_SATIR_GENISLIK { get; set; }
        public Nullable<bool> AJANDA_12SAATLIK_DILIM { get; set; }
        public Nullable<bool> KULLANICI_CANLI { get; set; }
        public Nullable<System.DateTime> SON_GORUNME_ZAMANI { get; set; }
        public Nullable<bool> ACTIVE_DIRECTORY_KULLAN { get; set; }
    }
}
