//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI_AKTIF
    {
        public long ID { get; set; }
        public Nullable<long> KULLANICI_ID { get; set; }
        public Nullable<bool> KULLANICI_CANLI { get; set; }
        public Nullable<System.DateTime> SON_GORUNME_ZAMANI { get; set; }
    }
}
