//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURULUM_KART_GRUP_BAG_DETAY
    {
        public long ID { get; set; }
        public Nullable<long> MODUL_ID { get; set; }
        public string MODUL_TURU { get; set; }
        public Nullable<long> KART_ID { get; set; }
        public string ALT_MODUL_ADI { get; set; }
        public string TABLO_ADI { get; set; }
        public string TASARIM_ADI { get; set; }
        public string ALAN_ADI { get; set; }
        public string KODLAMA { get; set; }
        public string GRUP_KODU { get; set; }
        public string GRUP_ADI { get; set; }
    }
}
