//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURULUM_ALAN
    {
        public long ID { get; set; }
        public string TABLO_ADI { get; set; }
        public Nullable<int> ALAN_SIRA { get; set; }
        public string ALAN_ADI { get; set; }
        public string ALAN_BASLIK { get; set; }
        public string ALAN_GRUP { get; set; }
        public string ALAN_TURU { get; set; }
        public Nullable<int> ALAN_BOY { get; set; }
        public Nullable<bool> VARSAYILAN_DEGER_UYGULA { get; set; }
        public string VARSAYILAN_DEGER { get; set; }
        public string GORUNUM_FORMAT { get; set; }
        public string MASKE_FORMAT { get; set; }
        public Nullable<int> LISTELEME_GENISLIK { get; set; }
        public Nullable<bool> GOSTER { get; set; }
        public Nullable<bool> DUZELT { get; set; }
        public Nullable<bool> GIZLI_ALAN { get; set; }
        public Nullable<bool> ARTAN_KOD_UYGULA { get; set; }
        public string ARTAN_KOD { get; set; }
        public Nullable<bool> ARTAN_KOD_EAN { get; set; }
        public Nullable<bool> BENZERSIZ_VERI { get; set; }
        public string LISTE_HIZALA { get; set; }
        public string LISTE_BASLIK_HIZALA { get; set; }
        public string ACILIR_KUTU_SABIT_BILGI { get; set; }
        public string MSSQL_CUMLE { get; set; }
        public Nullable<bool> BOS_OLAMAZ { get; set; }
        public string KOD { get; set; }
        public string SABIT_LISTE { get; set; }
        public string TABLODAN_LISTE_GETIR { get; set; }
        public string KOD_LISTE_GETIR { get; set; }
        public string KOD_LISTE_PARAMETRE { get; set; }
        public Nullable<int> ONDALIK_HANE { get; set; }
        public string SONA_BILGI { get; set; }
        public string BASA_BILGI { get; set; }
        public Nullable<int> EN_AZ { get; set; }
        public Nullable<int> EN_FAZLA { get; set; }
        public string TOPLAM_ISLEV { get; set; }
        public string SON_DUZENLEME_YAPAN { get; set; }
        public Nullable<System.DateTime> SON_DUZENLEME_ZAMANI { get; set; }
        public string HINT_IPUCU { get; set; }
        public Nullable<bool> SIFRE_GIRIS { get; set; }
        public Nullable<int> SEC_LISTE_GETIR { get; set; }
        public string SEC_LISTE_TANIMLARDAN { get; set; }
        public string BUYUK_HARF_SEC { get; set; }
        public Nullable<bool> SANAL_ALAN { get; set; }
        public Nullable<bool> KARAKTER_KONTROL { get; set; }
        public string KULLAN_KARAKTER { get; set; }
        public Nullable<bool> ARAMADA_KULLAN { get; set; }
    }
}
