//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURULUM_TABLO
    {
        public long ID { get; set; }
        public string TABLO_ADI { get; set; }
        public string TABLO_BASLIK { get; set; }
        public string TABLO_KISALTMA { get; set; }
        public Nullable<bool> TABLO_GIZLE { get; set; }
        public string ANA_ALAN_BENZERSIZ { get; set; }
        public string SON_DUZENLEME_YAPAN { get; set; }
        public Nullable<System.DateTime> SON_DUZENLEME_ZAMANI { get; set; }
    }
}
