//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MALZEME_KART
    {
        public long ID { get; set; }
        public string MALZEME_ADI { get; set; }
        public string MALZEME_GRUBU { get; set; }
        public string BIRIM { get; set; }
        public string MALZEME_CINSI { get; set; }
    }
}
