//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mat
    {
        public long ID { get; set; }
        public string proje_adi { get; set; }
        public string sensor_adi { get; set; }
        public System.DateTime tarih { get; set; }
        public string sicaklik { get; set; }
        public int olgunluk { get; set; }
        public int dayanim { get; set; }
        public string test_suresi { get; set; }
        public string extra_sure { get; set; }
        public string panel_tipi { get; set; }
        public Nullable<int> ortam_sicaklik { get; set; }
    }
}
