//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESAJ_GOREV_ALICILAR
    {
        public long ID { get; set; }
        public Nullable<long> MESAJ_ID { get; set; }
        public Nullable<long> ALICI_ID { get; set; }
        public string ALICI { get; set; }
        public Nullable<bool> OKUNDU { get; set; }
        public Nullable<System.DateTime> OKUNDU_TARIH { get; set; }
        public Nullable<bool> GOREV_TAMAM { get; set; }
        public Nullable<System.DateTime> GOREV_TARIH { get; set; }
        public Nullable<bool> SIL { get; set; }
    }
}
