//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESAJ_GOREV
    {
        public long ID { get; set; }
        public Nullable<long> GONDEREN_ID { get; set; }
        public string GONDEREN { get; set; }
        public Nullable<System.DateTime> GONDERIM_ZAMANI { get; set; }
        public string KONU { get; set; }
        public string MESAJ { get; set; }
        public string TURU { get; set; }
        public string ONCELIK { get; set; }
    }
}
