//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTAJ_FIS
    {
        public long ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_TARIH { get; set; }
        public Nullable<System.DateTime> MONTAJ_TARIH { get; set; }
        public string MONTAJ_NO { get; set; }
        public Nullable<double> MONTAJ_POZ_MIKTAR { get; set; }
        public Nullable<double> MONTAJ_M2 { get; set; }
        public string SANTIYE_SEFI { get; set; }
        public string MONTAJ_SORUMLUSU { get; set; }
        public string TASERON_FIRMA { get; set; }
        public Nullable<long> TASERON_ID { get; set; }
        public string MONTAJ_FIS_ACIKLAMA { get; set; }
        public Nullable<System.DateTime> MONTAJ_BASLAMA_ZAMANI { get; set; }
        public Nullable<System.DateTime> MONTAJ_BITIS_ZAMANI { get; set; }
        public Nullable<double> MONTAJ_TON { get; set; }
    }
}
