//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlgunlukCihazi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OlgunlukCihazi()
        {
            this.OlgunlukSensor = new HashSet<OlgunlukSensor>();
        }
    
        public int ID { get; set; }
        public string pozBarkod { get; set; }
        public Nullable<int> olgunluk_Baslangic { get; set; }
        public Nullable<int> olgunluk_Bitis { get; set; }
        public string kalip_Turu { get; set; }
        public string kalip_Tipi { get; set; }
        public Nullable<int> extra_Sure { get; set; }
        public Nullable<double> baslangic_Sicaklik { get; set; }
        public string hammadde_Tipi { get; set; }
        public string notDurum { get; set; }
        public string projeAdi { get; set; }
        public string poz { get; set; }
        public string cihaz_no { get; set; }
        public string testi_baslatan { get; set; }
        public Nullable<System.DateTime> test_tarihi { get; set; }
        public Nullable<bool> test_durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OlgunlukSensor> OlgunlukSensor { get; set; }
    }
}
