//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlgunlukSensor
    {
        public int ID { get; set; }
        public Nullable<int> testID { get; set; }
        public string cihaz_no { get; set; }
        public Nullable<double> sensor_sicaklik { get; set; }
        public Nullable<double> ortam_sicaklik { get; set; }
        public Nullable<double> olgunluk { get; set; }
        public Nullable<double> basinc_dayanimi { get; set; }
        public Nullable<double> egilme_dayanimi { get; set; }
        public Nullable<int> test_sure { get; set; }
        public Nullable<System.DateTime> sensor_tarih { get; set; }
    
        public virtual OlgunlukCihazi OlgunlukCihazi { get; set; }
    }
}
