//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_PERSONEL_KAPI_HAREKETLERI
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> ZAMAN { get; set; }
        public string GUN { get; set; }
        public string ADI_SOYADI { get; set; }
        public Nullable<long> PERSONEL_ID { get; set; }
        public Nullable<System.DateTime> BILGI_AKTARIM_TARIH { get; set; }
        public string BILGI_AKTARIM_NO { get; set; }
        public Nullable<long> CIHAZ_ID { get; set; }
    }
}
