//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_ZIYARETCI_GIRIS_KART
    {
        public long ID { get; set; }
        public string ZIYARETCI_KART_NO { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
        public string ADI_SOYADI { get; set; }
        public string EMANET_NO { get; set; }
        public string EMANET_TURU { get; set; }
        public string TC_NO { get; set; }
        public string TELEFON { get; set; }
        public string E_POSTA { get; set; }
        public string FIRMA_ADI { get; set; }
        public string KIME_GELDI { get; set; }
        public Nullable<bool> CIKIS_YAPTI { get; set; }
        public Nullable<System.DateTime> CIKIS_ZAMANI { get; set; }
        public string ZIYARETCI_ACIKLAMASI { get; set; }
    }
}
