//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_CALISMA_DUZENLERI
    {
        public long ID { get; set; }
        public string ADI { get; set; }
        public Nullable<long> VARDIYA_SAY { get; set; }
        public string ACIKLAMA { get; set; }
        public string CD_GRUP { get; set; }
        public Nullable<bool> HAFTA_SONU { get; set; }
        public Nullable<double> VARSAYILAN_CALISMA_ZAMAN { get; set; }
    }
}
