//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_PERSONEL_PUANTAJ
    {
        public long ID { get; set; }
        public Nullable<long> PERSONEL_ID { get; set; }
        public Nullable<long> HAFTALIK_PLAN_ID { get; set; }
        public Nullable<long> CALISMA_DUZEN_ID { get; set; }
        public string DURUM { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string GUN { get; set; }
        public Nullable<bool> HATA { get; set; }
        public Nullable<double> CALISMA_SAAT { get; set; }
        public Nullable<double> GEC_GELIS { get; set; }
        public Nullable<double> ERKEN_CIKIS { get; set; }
        public Nullable<double> FAZLA_MESAI_SAAT { get; set; }
        public Nullable<double> IZIN_SAAT { get; set; }
        public Nullable<bool> TATIL { get; set; }
        public Nullable<bool> GELMEDI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> IZIN_UCRETSIZ_SAAT { get; set; }
        public Nullable<double> FAZLA_MESAI_H_SONU_SAAT { get; set; }
        public Nullable<bool> SAAT_YUVARLA { get; set; }
        public Nullable<bool> HAFTA_SONU { get; set; }
        public Nullable<bool> GUNLUK_IZINLI { get; set; }
        public Nullable<bool> HAKEDILMEYEN_HAFTA_SONU { get; set; }
        public Nullable<double> DEVAMSIZLIK_SAAT { get; set; }
        public Nullable<double> GEREKEN_CALISMA_SAAT { get; set; }
        public Nullable<double> HAFTA_TATIL_SAAT { get; set; }
        public Nullable<double> RESMI_TATIL_SAAT { get; set; }
    }
}
