//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_TATIL_PLANLARI
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> BASLANGIC_GUN { get; set; }
        public Nullable<System.DateTime> BITIS_GUN { get; set; }
        public string TATIL_ADI { get; set; }
        public string TATIL_ACIKLAMASI { get; set; }
        public string TATIL_TIPI { get; set; }
        public string TATILDE_UYG_CALISMA_DUZEN { get; set; }
        public Nullable<long> CALISMA_DUZEN_ID { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
    }
}
