//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_PERSONEL_PUANTAJ_IZIN
    {
        public long ID { get; set; }
        public Nullable<long> PERSONEL_ID { get; set; }
        public Nullable<long> PUANTAJ_ID { get; set; }
        public Nullable<long> IZIN_ID { get; set; }
        public Nullable<long> IZIN_TANIM_ID { get; set; }
    }
}
