//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_CALISMA_DUZENLERI_HAFTALIK
    {
        public long ID { get; set; }
        public string ADI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
        public string OLUSTURAN { get; set; }
        public string PAZARTESI { get; set; }
        public Nullable<long> PAZARTESI_ID { get; set; }
        public string SALI { get; set; }
        public Nullable<long> SALI_ID { get; set; }
        public string CARSAMBA { get; set; }
        public Nullable<long> CARSAMBA_ID { get; set; }
        public string PERSEMBE { get; set; }
        public Nullable<long> PERSEMBE_ID { get; set; }
        public string CUMA { get; set; }
        public Nullable<long> CUMA_ID { get; set; }
        public string CUMARTESI { get; set; }
        public Nullable<long> CUMARTESI_ID { get; set; }
        public string PAZAR { get; set; }
        public Nullable<long> PAZAR_ID { get; set; }
    }
}
