//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_CALISMA_DUZENLERI_ALT
    {
        public long ID { get; set; }
        public Nullable<long> CALISMA_DUZEN_ID { get; set; }
        public string VARDIYA_SIRA { get; set; }
        public string TURU { get; set; }
        public Nullable<System.DateTime> BASLAMA_ZAMANI { get; set; }
        public string BASLAMA_GUNU { get; set; }
        public Nullable<System.DateTime> BITIS_ZAMANI { get; set; }
        public string BITIS_GUNU { get; set; }
        public Nullable<System.DateTime> SURE { get; set; }
        public Nullable<double> SURE_SAAT { get; set; }
        public Nullable<long> ERKEN_GIRIS_TOLERANS { get; set; }
        public Nullable<long> GEC_GIRIS_TOLERANS { get; set; }
        public Nullable<long> ERKEN_CIKIS_TOLERANS { get; set; }
        public Nullable<long> GEC_CIKIS_TOLERANS { get; set; }
        public Nullable<long> ARTI_KATSAYI { get; set; }
        public Nullable<long> EKSI_KATSAYI { get; set; }
    }
}
