//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_ZIYARETCI_KART
    {
        public long ID { get; set; }
        public string ZIYARETCI_KART_NO { get; set; }
        public Nullable<bool> CIHAZA_GONDER { get; set; }
        public string GRUP { get; set; }
    }
}
