//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKS_CIHAZ
    {
        public long ID { get; set; }
        public string GRUP { get; set; }
        public string CIHAZ_ADI { get; set; }
        public string IP { get; set; }
        public string PORT { get; set; }
        public string TURU { get; set; }
        public string CIHAZ_ID { get; set; }
        public string CIHAZ_MODEL { get; set; }
        public Nullable<bool> PERSONEL_BILGISI_GONDER { get; set; }
        public Nullable<System.DateTime> PERSONEL_BILGI_GONDER_KONTROL_ZAMAN { get; set; }
        public Nullable<long> PERSONEL_BILGI_GONDER_KONTROL_DK { get; set; }
        public string ILETISIM_DURUMU { get; set; }
        public string ILETISIM_LOG { get; set; }
        public Nullable<System.DateTime> SON_ILETISIM_ZAMANI { get; set; }
        public Nullable<bool> CIHAZ_ILETISIM_HATA { get; set; }
        public Nullable<bool> CIHAZ_AKTIF { get; set; }
        public Nullable<int> CIHAZ_ILETISIM_KONTROL_DK { get; set; }
    }
}
