//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PERA_FIBROEntities : DbContext
    {
        public PERA_FIBROEntities()
            : base("name=PERA_FIBROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARSIV_DOKUMAN> ARSIV_DOKUMAN { get; set; }
        public virtual DbSet<BOLUMLER> BOLUMLER { get; set; }
        public virtual DbSet<KALIP_DOKUM_YUZEY> KALIP_DOKUM_YUZEY { get; set; }
        public virtual DbSet<KALIP_FRAME_TEDARIK> KALIP_FRAME_TEDARIK { get; set; }
        public virtual DbSet<KALIP_IS_EMRI> KALIP_IS_EMRI { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_3D_TARAMA> KALIP_IS_EMRI_3D_TARAMA { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_DOKUM> KALIP_IS_EMRI_DOKUM { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_DOKUM_3D_TARAMA> KALIP_IS_EMRI_DOKUM_3D_TARAMA { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_DOKUM_DURUM> KALIP_IS_EMRI_DOKUM_DURUM { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_DOKUM_LOG> KALIP_IS_EMRI_DOKUM_LOG { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_DURUM> KALIP_IS_EMRI_DURUM { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_KALIP_OLUSTUR> KALIP_IS_EMRI_KALIP_OLUSTUR { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_KALITE> KALIP_IS_EMRI_KALITE { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_POZ> KALIP_IS_EMRI_POZ { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_ROTA> KALIP_IS_EMRI_ROTA { get; set; }
        public virtual DbSet<KULLANICI> KULLANICI { get; set; }
        public virtual DbSet<PROJE_BLOK> PROJE_BLOK { get; set; }
        public virtual DbSet<PROJE_BLOK_CEPHE> PROJE_BLOK_CEPHE { get; set; }
        public virtual DbSet<PROJE_DOKUM_HEDEF> PROJE_DOKUM_HEDEF { get; set; }
        public virtual DbSet<PROJE_KART> PROJE_KART { get; set; }
        public virtual DbSet<PROJE_MONTAJ_HEDEF> PROJE_MONTAJ_HEDEF { get; set; }
        public virtual DbSet<PROJE_SANTIYE> PROJE_SANTIYE { get; set; }
        public virtual DbSet<PROJE_SIPARIS_HEDEF> PROJE_SIPARIS_HEDEF { get; set; }
        public virtual DbSet<PROJE_TASERON> PROJE_TASERON { get; set; }
        public virtual DbSet<SEVK_ALT> SEVK_ALT { get; set; }
        public virtual DbSet<SEVK_FIS> SEVK_FIS { get; set; }
        public virtual DbSet<SIPARIS_PLAN> SIPARIS_PLAN { get; set; }
        public virtual DbSet<SIPARIS_POZ> SIPARIS_POZ { get; set; }
        public virtual DbSet<SIPARIS_POZ_REVIZYON> SIPARIS_POZ_REVIZYON { get; set; }
        public virtual DbSet<SIPARIS_FORM> SIPARIS_FORM { get; set; }
    }
}
