//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_EGITIM_PLAN
    {
        public long ID { get; set; }
        public string TURU { get; set; }
        public string ADI { get; set; }
        public string GRUP { get; set; }
        public string SINIF_ADI { get; set; }
        public Nullable<System.DateTime> BASLANGIC_ZAMANI { get; set; }
        public Nullable<System.DateTime> BITIS_ZAMANI { get; set; }
        public Nullable<long> SURESI { get; set; }
        public string EGITIM_FIRMASI { get; set; }
        public string EGITMEN { get; set; }
        public string EGITIM_YERI { get; set; }
        public string EGITIM_ADRESI { get; set; }
        public string EGITIM_ACIKLAMASI { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
        public string OLUSTURAN { get; set; }
    }
}
