//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_IZIN_TANIMLARI
    {
        public long ID { get; set; }
        public string IZIN_GRUP { get; set; }
        public string IZIN_ADI { get; set; }
        public string IZIN_TANIM_ACIKLAMASI { get; set; }
        public string IZIN_TIPI { get; set; }
        public string UCRET_TIPI { get; set; }
        public Nullable<bool> HAFTA_SONU_DAHIL { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
        public string OLUSTURAN { get; set; }
    }
}
