//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_MASRAF
    {
        public long ID { get; set; }
        public Nullable<long> PERSONEL_ID { get; set; }
        public string DURUM { get; set; }
        public Nullable<System.DateTime> FATURA_FIS_TARIH { get; set; }
        public string FATURA_FIS_NO { get; set; }
        public string MASRAF_TURU { get; set; }
        public string MASRAF_ACIKLAMASI { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<bool> ONAY { get; set; }
        public Nullable<System.DateTime> ONAYLAMA_TARIH { get; set; }
        public string ONAYLAYAN { get; set; }
        public Nullable<bool> IPTAL { get; set; }
        public Nullable<System.DateTime> IPTAL_ZAMANI { get; set; }
        public string IPTAL_EDEN { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<long> OLUSTURAN_ID { get; set; }
        public string SONUC_ACIKLAMASI { get; set; }
    }
}
