//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_ACIK_POZISYON
    {
        public long ID { get; set; }
        public string ILAN_ADI { get; set; }
        public string ILAN_KODU { get; set; }
        public string ILAN_DURUMU { get; set; }
        public string CALISMA_SEKLI { get; set; }
        public string PERSONEL_GRUBU { get; set; }
        public string DEPARTMAN { get; set; }
        public Nullable<long> PERSONEL_SAYISI { get; set; }
        public Nullable<bool> ENGELLI_ILANI { get; set; }
        public string ISIN_TANIMI { get; set; }
        public string ARANAN_NITELIKLER { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<long> OLUSTURAN_ID { get; set; }
    }
}
