//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_OZGECMIS
    {
        public long ID { get; set; }
        public Nullable<long> PERSONEL_ID { get; set; }
        public string BILGI_TURU { get; set; }
        public string BILGI_ADI { get; set; }
        public string BILGI_ACIKLAMASI { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_ZAMANI { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<long> OLUSTURAN_ID { get; set; }
    }
}
