//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_KART
    {
        public long ID { get; set; }
        public string BARKOD { get; set; }
        public string TC_NO { get; set; }
        public string ADI_SOYADI { get; set; }
        public Nullable<System.DateTime> IS_BAS_TARIH { get; set; }
        public string BOLUM { get; set; }
        public string TELEFON { get; set; }
        public string E_POSTA { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIL_DURUM_ILETISIM { get; set; }
        public Nullable<bool> ISTEN_CIKTI { get; set; }
        public string KAN_GRUBU { get; set; }
        public Nullable<System.DateTime> CIKIS_TARIH { get; set; }
        public string CEP_TELEFON { get; set; }
        public string TEL_DAHILI { get; set; }
        public string CALISMA_SEKLI { get; set; }
        public string GRUP { get; set; }
        public string UNVAN { get; set; }
        public Nullable<System.DateTime> DOGUM_TARIH { get; set; }
        public string CINSIYET { get; set; }
        public string UYRUK { get; set; }
        public string MEDENI_HAL { get; set; }
        public Nullable<double> COCUK_SAYISI { get; set; }
        public Nullable<bool> ENGELLI { get; set; }
        public string ADRES { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string BANKA_ADI { get; set; }
        public string SUBE_ADI_KODU { get; set; }
        public string HESAP_NUMARASI { get; set; }
        public string IBAN { get; set; }
        public string IS_TELEFON { get; set; }
        public string ULKE { get; set; }
        public string EHLIYET { get; set; }
        public string GOREVI { get; set; }
        public string SGK_SICIL_KODU { get; set; }
        public string DOGUM_YERI { get; set; }
        public string ANA_ADI { get; set; }
        public string BABA_ADI { get; set; }
        public string DIN { get; set; }
        public string K_IL { get; set; }
        public string K_ILCE { get; set; }
        public string K_ULKE { get; set; }
        public string K_MAHALLE_KOY { get; set; }
        public string CILT_NO { get; set; }
        public string SAYFA_NO { get; set; }
        public string KUTUK_SIRA_NO { get; set; }
        public string CUZDAN_SIRA_NO { get; set; }
        public string SAGLIK_NOTLARI { get; set; }
        public string PDKS_KART_KODU { get; set; }
        public string SERVIS_BILGISI { get; set; }
        public string EKIP { get; set; }
        public string ISTEN_CIKIS_NEDENI { get; set; }
        public string SON_MEZUNIYET_OKUL { get; set; }
        public string SON_MEZUNIYET_BOLUM { get; set; }
        public byte[] RESIM { get; set; }
        public Nullable<System.DateTime> PERSONEL_BASVURU_TARIH { get; set; }
        public Nullable<bool> PERSONEL_ADAYI { get; set; }
        public Nullable<long> PERSONEL_ILAN_ID { get; set; }
        public string DEPARTMAN { get; set; }
        public string PERSONEL_ADAY_DEGERLENDIRME_DURUM { get; set; }
        public string PERSONEL_ADAY_DEGERLENDIRME_MULAKAT_DURUM { get; set; }
        public string PERSONEL_ADAY_DEGERLENDIRME_ACIKLAMA { get; set; }
        public Nullable<bool> CIHAZA_GONDER { get; set; }
        public Nullable<double> MESAI_UYGULAMA_TIPI { get; set; }
        public string PERSONEL_TURU { get; set; }
    }
}
