//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class POZ_SIPARIS
    {
        public long ID { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string SIPARIS_TURU { get; set; }
        public string BLOK_ADI { get; set; }
        public string CEPHE_ADI { get; set; }
        public string KAT_ADI { get; set; }
        public Nullable<double> SIPARIS_MIKTAR { get; set; }
        public Nullable<double> REV_EKSI { get; set; }
        public Nullable<double> SON_SIPARIS_MIKTAR { get; set; }
        public Nullable<double> URETIM_MIKTAR { get; set; }
        public Nullable<double> SEVK_MIKTAR { get; set; }
        public Nullable<double> MONTAJ_MIKTAR { get; set; }
        public Nullable<double> TOP_SIP_M2 { get; set; }
        public Nullable<double> TOPLAM_HACIM { get; set; }
        public Nullable<double> TOP_DOKUM_M2 { get; set; }
        public Nullable<double> TOPLAM_MT { get; set; }
        public Nullable<double> REV_ARTI { get; set; }
        public Nullable<double> PLANLANAN_MIKTAR { get; set; }
        public Nullable<double> KALAN_PLAN_MIKTAR { get; set; }
    }
}
