//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class POZ_REVIZYON
    {
        public long ID { get; set; }
        public Nullable<double> PROJE_ID { get; set; }
        public Nullable<double> POZ_ID { get; set; }
        public Nullable<System.DateTime> REVIZYON_TARIH { get; set; }
        public string REVIZYON_NO { get; set; }
        public string REVIZYON_ALAN { get; set; }
        public string REVIZYON_BILGI { get; set; }
        public string REVIZYON_ACIKLAMA { get; set; }
        public string ONCEKI_BILGI { get; set; }
        public Nullable<double> SIPARIS_POZ_ID { get; set; }
        public string REVIZYON_YAPAN { get; set; }
    }
}
