//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class POZ_KART_NP
    {
        public long ID { get; set; }
        public Nullable<double> PROJE_ID { get; set; }
        public string POZ_TURU { get; set; }
        public string POZ_NO { get; set; }
        public string POZ_ADI { get; set; }
        public Nullable<double> BOY { get; set; }
        public Nullable<double> EN { get; set; }
        public string RENK { get; set; }
        public string MALZEME_YUZEYI { get; set; }
        public string MALZEME_GRUP { get; set; }
        public string MALZEME_CINSI { get; set; }
        public string MALZEME_ADI { get; set; }
        public string POZ_ACIKLAMASI { get; set; }
        public string BIRIM { get; set; }
        public Nullable<double> BIRIM_M2 { get; set; }
        public Nullable<double> POZ_TOP_SIP_M2 { get; set; }
        public Nullable<double> DOKUM_M2 { get; set; }
        public Nullable<double> POZ_TOP_DOKUM_M2 { get; set; }
        public Nullable<double> MT { get; set; }
        public Nullable<double> POZ_TOPLAM_MT { get; set; }
        public Nullable<double> ONGORULEN_URUN_AGIRLIK { get; set; }
        public Nullable<double> KESIT_ACILIMI { get; set; }
        public Nullable<double> KESIT_ACILIM_ARTI { get; set; }
        public Nullable<double> KESIT_ACILIM_EKSI { get; set; }
        public Nullable<double> ONCELIK_SIRASI { get; set; }
        public string FRAME_DURUMU { get; set; }
        public Nullable<double> FRAME_KG { get; set; }
        public Nullable<bool> YUZ_ISL_VAR { get; set; }
        public Nullable<bool> GALVENIZE_GITMELI { get; set; }
        public Nullable<bool> MONTAJSIZ { get; set; }
        public Nullable<bool> POZ_IPTAL { get; set; }
        public Nullable<bool> HOLD { get; set; }
        public Nullable<double> POZ_SIPARIS_MIKTAR { get; set; }
        public Nullable<double> POZ_REV_EKSI { get; set; }
        public Nullable<double> POZ_SON_SIPARIS_MIKTAR { get; set; }
        public Nullable<double> POZ_URETIM_MIKTAR { get; set; }
        public Nullable<double> POZ_SEVK_MIKTAR { get; set; }
        public Nullable<double> POZ_MONTAJ_MIKTAR { get; set; }
        public string SON_REV_NO { get; set; }
        public string REPORT_CODE { get; set; }
        public Nullable<double> ILK_EN { get; set; }
        public Nullable<double> ILK_BOY { get; set; }
        public Nullable<double> ILK_BIRIM_M2 { get; set; }
        public string ILK_DOKUM_RENGI { get; set; }
        public string ILK_MALZEME_YUZEYI { get; set; }
        public string ILK_MALZEME_GRUP { get; set; }
        public string ILK_MALZEME_CINSI { get; set; }
        public string ILK_POZ_NO { get; set; }
        public string ILK_MALZEME_ADI { get; set; }
        public string ILK_POZ_TURU { get; set; }
        public Nullable<double> ILK_HACIM { get; set; }
        public Nullable<double> BIRIM_HACIM { get; set; }
        public Nullable<double> POZ_TOPLAM_HACIM { get; set; }
        public string YUZEY_ISLEM_1 { get; set; }
        public string YUZEY_ISLEM_1_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_2 { get; set; }
        public string YUZEY_ISLEM_2_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_3 { get; set; }
        public string YUZEY_ISLEM_3_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_4_ACIKLAMA { get; set; }
        public string YUZEY_ISLEM_4 { get; set; }
        public string YUZEY_ISLEM_5 { get; set; }
        public string YUZEY_ISLEM_5_ACIKLAMA { get; set; }
        public Nullable<bool> MODEL_UYGUNLUK { get; set; }
        public string MODEL_UYG_ONAY_VEREN { get; set; }
        public Nullable<System.DateTime> MODEL_UYG_ONAY_TARIH { get; set; }
        public string POZ_BARKOD { get; set; }
        public Nullable<double> POZ_REV_ARTI { get; set; }
        public Nullable<double> FRAME_SIPARIS_MIKTAR { get; set; }
        public Nullable<double> FRAME_KABUL_BEKLE_MIKTAR { get; set; }
        public Nullable<double> FRAME_GELEN_MIKTAR { get; set; }
        public Nullable<double> FRAME_GALVENIZLI_MIKTAR { get; set; }
        public Nullable<double> FRAME_GALVENIZ_BEKLE_MIKTAR { get; set; }
        public Nullable<double> FRAME_KULLAN_MIKTAR { get; set; }
        public Nullable<double> FRAME_MUSAIT_MIKTAR { get; set; }
        public Nullable<double> FRAME_EKSIK_TEMIN { get; set; }
        public string FRAME_TURU { get; set; }
        public Nullable<double> KALIP_TASARIM_SAYISI { get; set; }
        public Nullable<double> IS_EMRI_SAYISI { get; set; }
        public string POZ_PLAN_MIKTAR { get; set; }
        public Nullable<bool> FRAME_DOSYA_YUKLENDI { get; set; }
        public string FRAME_DOSYA_YUKLENDI_YAPAN { get; set; }
        public Nullable<System.DateTime> FRAME_DOSYA_YUKLENDI_TARIH { get; set; }
    }
}
