//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJE_TASERON
    {
        public long ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string TASERON_ADI { get; set; }
        public string YETKILI_ADI { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
