//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJE_BLOK_CEPHE
    {
        public long ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string BLOK_ADI { get; set; }
        public string CEPHE_ADI { get; set; }
        public Nullable<double> CEPHE_M2 { get; set; }
        public Nullable<long> CEPHE_ADET { get; set; }
        public Nullable<long> UYGULAMA_ADET { get; set; }
        public Nullable<double> UYGULAMA_M2 { get; set; }
    }
}
