//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAPOR_DIZAYN
    {
        public long ID { get; set; }
        public string TURU { get; set; }
        public string RAPOR_ADI { get; set; }
        public string RAPOR_DOSYASI { get; set; }
        public Nullable<bool> NOKTA_VURUSLU { get; set; }
    }
}
