//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIM_YONETIM
    {
        public long ID { get; set; }
        public Nullable<long> MODUL_ID { get; set; }
        public string MODUL_TURU { get; set; }
        public Nullable<long> KART_ID { get; set; }
        public Nullable<long> VERI_ID { get; set; }
        public Nullable<bool> VITRIN_RESIM { get; set; }
        public string RESIM_ADI { get; set; }
        public string DOSYA_YOLU { get; set; }
        public string KLASOR_YOLU { get; set; }
        public string SON_GUNCELLEME { get; set; }
        public Nullable<System.DateTime> SON_GUNCELLEME_TARIH { get; set; }
    }
}
