//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVK_TALEP_POZ
    {
        public long ID { get; set; }
        public Nullable<long> TALEP_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> SEVK_ALT_ID { get; set; }
        public Nullable<double> TALEP_EDILEN_MIKTAR { get; set; }
        public Nullable<double> SEVK_EDILEN_MIKTAR { get; set; }
        public Nullable<double> KALAN_TALEP_MIKTAR { get; set; }
    }
}
