//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVK_SANDIKLAMA_FIS
    {
        public long ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<System.DateTime> SANDIKLAMA_TARIH { get; set; }
        public string SANDIK_BARKODU { get; set; }
        public string SANDIK_PALET { get; set; }
        public string SANDIKLAMA_ACIKLAMASI { get; set; }
        public string PERSONEL_ADI { get; set; }
        public Nullable<double> SANDIK_TOPLAM_M2 { get; set; }
        public Nullable<double> SANDIK_TOPLAM_ADET { get; set; }
        public Nullable<double> SANDIK_TOPLAM_KG { get; set; }
        public string RAF_KONUM { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUSTURMA_TARIH { get; set; }
        public Nullable<long> DEPO_ID { get; set; }
        public string DEPO_ADI { get; set; }
        public string FIS_DURUMU { get; set; }
        public Nullable<double> EN { get; set; }
        public Nullable<double> BOY { get; set; }
        public Nullable<double> YUKSEKLIK { get; set; }
        public Nullable<double> M3 { get; set; }
        public Nullable<double> BOS_SANDIK_KG { get; set; }
    }
}
