//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVK_POZ
    {
        public long ID { get; set; }
        public Nullable<long> SEVK_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<double> PLAN_SEVK_MIKTAR { get; set; }
        public Nullable<double> SEVK_EDILEN_MIKTAR { get; set; }
        public Nullable<double> KALAN_SEVK_MIKTAR { get; set; }
        public Nullable<double> INDIRILEN_MIKTAR { get; set; }
        public Nullable<double> KALAN_INDIR_MIKTAR { get; set; }
        public Nullable<double> MONTAJ_MIKTAR { get; set; }
        public Nullable<double> KALAN_MONTAJ_MIKTAR { get; set; }
    }
}
