//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVK_FIRMA_YETKILI
    {
        public long ID { get; set; }
        public Nullable<long> CARI_ID { get; set; }
        public string YETKILI_ADI { get; set; }
        public string YETKILI_GOREVI { get; set; }
        public string YETKILI_TELEFON { get; set; }
        public string YETKILI_TELEFON_DAHILI { get; set; }
        public string YETKILI_GSM { get; set; }
        public string YETKILI_ACIKLAMASI { get; set; }
        public string YETKILI_E_MAIL { get; set; }
    }
}
