//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVK_ALT
    {
        public long ID { get; set; }
        public Nullable<long> SEVK_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> MIKTAR { get; set; }
        public string POZ_NO { get; set; }
        public Nullable<long> EN { get; set; }
        public Nullable<long> BOY { get; set; }
        public string MALZEME_ADI { get; set; }
        public string RENK { get; set; }
        public string YUZEY { get; set; }
        public Nullable<long> SEVK_EDILEN_MIKTAR { get; set; }
        public Nullable<long> KAL_SEVK_MIKTAR { get; set; }
        public string SANDIK_PALET { get; set; }
        public Nullable<double> BIRIM_M2 { get; set; }
        public string MALZEME_CINSI { get; set; }
        public Nullable<long> SIRA_NO { get; set; }
    }
}
