//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS_POZ_REVIZYON
    {
        public long ID { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public string POZ_NO { get; set; }
        public string REVIZYON_NO { get; set; }
        public string REVIZYON_TURU { get; set; }
        public Nullable<long> REVIZYON_MIKTAR { get; set; }
        public string REVIZYON_ACIKLAMA { get; set; }
        public Nullable<System.DateTime> REVIZYON_TARIH { get; set; }
        public Nullable<long> SIPARIS_EXCEL_ID { get; set; }
        public Nullable<bool> EN_BOY_REV { get; set; }
        public Nullable<long> EN { get; set; }
        public Nullable<long> BOY { get; set; }
        public Nullable<bool> m2_REV { get; set; }
        public Nullable<double> BIRIM_M2 { get; set; }
        public Nullable<bool> DIGER_REVIZYON { get; set; }
        public string DIGER_REVIZYON_TURU { get; set; }
        public string REVIZYON_BILGISI { get; set; }
    }
}
