//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS_FORM
    {
        public long ID { get; set; }
        public string SIPARIS_NO { get; set; }
        public Nullable<System.DateTime> SIPARIS_TARIH { get; set; }
        public Nullable<System.DateTime> TESLIM_TARIH { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string SIPARIS_ACIKLAMASI { get; set; }
        public string SIPARIS_DURUM { get; set; }
        public string SIPARIS_BARKOD { get; set; }
        public Nullable<System.DateTime> MONTAJ_TARIH { get; set; }
    }
}
