//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS_POZ
    {
        public long ID { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public string MALZEME_GRUP { get; set; }
        public string POZ_NO { get; set; }
        public string POZ_ADI { get; set; }
        public string MALZEME_ADI { get; set; }
        public Nullable<long> BOY { get; set; }
        public Nullable<long> EN { get; set; }
        public string RENK { get; set; }
        public string YUZEY { get; set; }
        public Nullable<long> ILK_SIPARIS_MIKTAR { get; set; }
        public Nullable<long> REV_ARTI { get; set; }
        public Nullable<long> REV_EKSI { get; set; }
        public Nullable<long> UYUMSUZ_ARTI { get; set; }
        public Nullable<long> SON_SIPARIS_MIKTAR { get; set; }
        public Nullable<long> URETIM_MIKTAR { get; set; }
        public Nullable<long> SEVK_MIKTAR { get; set; }
        public Nullable<bool> POZ_IPTAL { get; set; }
        public string BIRIM { get; set; }
        public Nullable<double> BIRIM_M2 { get; set; }
        public Nullable<double> TOP_M2 { get; set; }
        public Nullable<double> KESIT_ACILIMI { get; set; }
        public Nullable<double> MT { get; set; }
        public Nullable<double> TOPLAM_MT { get; set; }
        public string SATIR_ACIKLAMASI { get; set; }
        public Nullable<long> ONCELIK_SIRASI { get; set; }
        public string SIPARIS_TURU { get; set; }
        public Nullable<long> SIPARIS_EXCEL_ID { get; set; }
        public string KALIP_NO_1 { get; set; }
        public string KALIP_NO_2 { get; set; }
        public string KALIP_NO_3 { get; set; }
        public string KALIP_NO_4 { get; set; }
        public string MALZEME_CINSI { get; set; }
        public Nullable<double> DOKUM_M2 { get; set; }
        public Nullable<double> TOP_DOKUM_M2 { get; set; }
        public Nullable<long> IS_EMRI_DOKUM_SAYI { get; set; }
        public Nullable<bool> HOLD { get; set; }
        public string SON_REV_NO { get; set; }
        public string SON_UYG_NO { get; set; }
        public Nullable<long> ILK_EN { get; set; }
        public Nullable<long> ILK_BOY { get; set; }
        public Nullable<double> ILK_BIRIM_M2 { get; set; }
        public Nullable<bool> YUZ_ISL_VAR { get; set; }
        public Nullable<double> KESIT_ACILIM_ARTI { get; set; }
        public Nullable<double> KESIT_ACILIM_EKSI { get; set; }
        public Nullable<long> EKSIK_FRAME_SIPARIS { get; set; }
        public Nullable<long> EKSIK_DOK_PLAN_SIPARIS { get; set; }
        public string FRAME_DURUMU { get; set; }
        public string YUZEY_ISLEM_ACIKLAMA { get; set; }
        public Nullable<double> FRAME_KG { get; set; }
        public Nullable<long> MONTAJ_MIKTAR { get; set; }
        public Nullable<bool> GALVENIZE_GITMELI { get; set; }
        public Nullable<bool> MONTAJSIZ { get; set; }
        public string ILK_DOKUM_RENGI { get; set; }
        public string ILK_YUZEY { get; set; }
        public string ILK_MALZEME_GRUP { get; set; }
        public string ILK_MALZEME_CINSI { get; set; }
        public string ILK_SIPARIS_TURU { get; set; }
        public string ILK_POZ_NO { get; set; }
        public string ILK_MALZEME_ADI { get; set; }
        public string BLOK_ADI { get; set; }
        public string CEPHE_ADI { get; set; }
        public string REPORT_CODE { get; set; }
        public Nullable<double> ONGORULEN_URUN_AGIRLIK { get; set; }
        public string POZ_TURU { get; set; }
    }
}
