//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public int user_id { get; set; }
        public string user_nick { get; set; }
        public string user_password { get; set; }
        public string user_department { get; set; }
        public string user_name { get; set; }
        public string user_role { get; set; }
        public string Confirmpwd { get; set; }
    }
}
