//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Taramalar
    {
        public long IDT { get; set; }
        public System.DateTime TarihT { get; set; }
        public string ProjeT { get; set; }
        public string BarkodT { get; set; }
        public string PozT { get; set; }
        public string MalzemeT { get; set; }
        public string YüzeyT { get; set; }
        public string DökümT { get; set; }
        public string CihazT { get; set; }
        public string KonuT { get; set; }
        public long SureT { get; set; }
        public long SureR { get; set; }
        public string TeslimT { get; set; }
        public int SayıT { get; set; }
        public string HataT { get; set; }
        public string DurumT { get; set; }
        public byte[] ResimT1 { get; set; }
        public byte[] ResimT2 { get; set; }
        public byte[] ResimT3 { get; set; }
        public byte[] ResimT4 { get; set; }
        public byte[] ResimT5 { get; set; }
        public byte[] ResimT6 { get; set; }
        public byte[] ResimT7 { get; set; }
        public byte[] ResimT8 { get; set; }
        public byte[] ResimT9 { get; set; }
        public byte[] ResimT10 { get; set; }
        public Nullable<decimal> AlanT { get; set; }
        public string TNot { get; set; }
        public string PozBarkodT { get; set; }
        public string RaporT { get; set; }
    }
}
