//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYGUNSUZLUK_RESIM
    {
        public long ID { get; set; }
        public Nullable<long> UYGUNSUZLUK_ID { get; set; }
        public string TURU { get; set; }
        public string ACIKLAMA { get; set; }
        public byte[] RESIM { get; set; }
        public Nullable<System.DateTime> EKLENME_ZAMANI { get; set; }
    }
}
