//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYGUNSUZLUK_FORM
    {
        public long ID { get; set; }
        public string UYGUNSUZLUK_TURU { get; set; }
        public string UYGUNSUZLUK_NO { get; set; }
        public string UYGUNSUZLUK_DURUMU { get; set; }
        public Nullable<System.DateTime> TESPIT_TARIH { get; set; }
        public string TESPIT_EDEN { get; set; }
        public Nullable<long> TESPIT_EDEN_ID { get; set; }
        public string TESPIT_EDILEN_YER { get; set; }
        public string TESPIT_EDEN_BOLUM { get; set; }
        public string BARKOD_TURU { get; set; }
        public string BARKOD { get; set; }
        public Nullable<long> DOKUM_ID { get; set; }
        public Nullable<long> POZ_ID { get; set; }
        public Nullable<long> KALIP_ID { get; set; }
        public Nullable<long> PROJE_ID { get; set; }
        public Nullable<long> FRAME_ID { get; set; }
        public string UYGUNSUZLUK_TANIMLARI { get; set; }
        public string TEKNIK_ACIKLAMA { get; set; }
        public string SEBEP_ACIKLAMA { get; set; }
        public string COZUM_ACIKLAMA { get; set; }
        public string ONLEYECI_ACIKLAMA { get; set; }
        public Nullable<bool> YAYINLA { get; set; }
        public Nullable<System.DateTime> YAYIN_TARIH { get; set; }
        public Nullable<bool> UYGUNSUZLUK_ISLEME_ALINDI { get; set; }
        public string UYGUNSUZLUK_ISLEME_ALAN { get; set; }
        public Nullable<System.DateTime> UYGUNSUZLUK_ISLEME_AL_TARIH { get; set; }
        public Nullable<long> UYGUNSUZLUK_ISLEME_ALAN_ID { get; set; }
        public string ANALIZ_PERSONELI { get; set; }
        public Nullable<long> ANALIZ_PERSONEL_ID { get; set; }
        public Nullable<System.DateTime> ANALIZ_SON_TARIH { get; set; }
        public Nullable<bool> UYARI_MAIL_GONDERILDI { get; set; }
        public Nullable<bool> ANALIZ_TAMAMLANDI { get; set; }
        public Nullable<System.DateTime> ANALIZ_TAMAM_TARIH { get; set; }
        public string SONUC_SECENEK_1 { get; set; }
        public string SONUC_SECENEK_2 { get; set; }
        public string SONUC_SECENEK_3 { get; set; }
        public Nullable<bool> UYGUNSUZLUK_GIDERILDI { get; set; }
        public string UYGUNSUZLUK_GIDERILDI_YAPAN { get; set; }
        public Nullable<System.DateTime> UYGUNSUZLUK_GIDERILDI_ZAMANI { get; set; }
        public Nullable<long> UYGUNSUZLUK_GIDERILDI_YAPAN_ID { get; set; }
        public Nullable<bool> KALITE_KONTROL_ONAY { get; set; }
        public string KALITE_KONTROL_ONAYLAYAN { get; set; }
        public Nullable<System.DateTime> KALITE_KONTROL_ONAY_TARIH { get; set; }
        public Nullable<long> KALITE_KONTROL_ONAYLAYAN_ID { get; set; }
        public Nullable<bool> UST_YONETICI_ONAY { get; set; }
        public string UST_YONETICI_ONAYLAYAN { get; set; }
        public Nullable<System.DateTime> UST_YONETICI_ONAY_TARIH { get; set; }
        public Nullable<long> UST_YONETICI_ONAYLAYAN_ID { get; set; }
        public Nullable<bool> UYGUNSUZLUK_KAPANDI { get; set; }
        public string UYGUNSUZLUK_KAPANDI_YAPAN { get; set; }
        public Nullable<System.DateTime> UYGUNSUZLUK_KAPANDI_TARIH { get; set; }
        public Nullable<long> UYGUNSUZLUK_KAPANDI_YAPAN_ID { get; set; }
        public string ONCEKI_DURUM { get; set; }
        public Nullable<long> YENI_OLUSAN_KALIP_ID { get; set; }
        public string ILGILI_BOLUM { get; set; }
    }
}
