//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalFibrobeton.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PERA_FIBRO_ULTIMATEEntities : DbContext
    {
        public PERA_FIBRO_ULTIMATEEntities()
            : base("name=PERA_FIBRO_ULTIMATEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KULLANICI_NP> KULLANICI { get; set; }
        public virtual DbSet<AJANDA> AJANDA { get; set; }
        public virtual DbSet<AYARLAR_DOKUM_ROTA> AYARLAR_DOKUM_ROTA { get; set; }
        public virtual DbSet<AYARLAR_GENEL> AYARLAR_GENEL { get; set; }
        public virtual DbSet<AYARLAR_TANIMLA> AYARLAR_TANIMLA { get; set; }
        public virtual DbSet<BARKOD_DIZAYN> BARKOD_DIZAYN { get; set; }
        public virtual DbSet<BOLUMLER_NP> BOLUMLER { get; set; }
        public virtual DbSet<DEPO> DEPO { get; set; }
        public virtual DbSet<DOKUM_IS_EMRI> DOKUM_IS_EMRI { get; set; }
        public virtual DbSet<DOKUM_IS_EMRI_DOKUM> DOKUM_IS_EMRI_DOKUM { get; set; }
        public virtual DbSet<DOKUM_IS_EMRI_DOKUM_DURUM> DOKUM_IS_EMRI_DOKUM_DURUM { get; set; }
        public virtual DbSet<DOKUM_IS_EMRI_DOKUM_TADILAT> DOKUM_IS_EMRI_DOKUM_TADILAT { get; set; }
        public virtual DbSet<DOKUM_IS_EMRI_POZ> DOKUM_IS_EMRI_POZ { get; set; }
        public virtual DbSet<DOKUMAN_YONETIM_LOG> DOKUMAN_YONETIM_LOG { get; set; }
        public virtual DbSet<DOVIZ> DOVIZ { get; set; }
        public virtual DbSet<DOVIZ_LOG> DOVIZ_LOG { get; set; }
        public virtual DbSet<E_POSTA_BILGILENDIR> E_POSTA_BILGILENDIR { get; set; }
        public virtual DbSet<FRAME_TEDARIK> FRAME_TEDARIK { get; set; }
        public virtual DbSet<FRAME_TEDARIK_TADILAT> FRAME_TEDARIK_TADILAT { get; set; }
        public virtual DbSet<FRAME_TEDARIKCI_KART> FRAME_TEDARIKCI_KART { get; set; }
        public virtual DbSet<FRAME_TEDARIKCI_YETKILI> FRAME_TEDARIKCI_YETKILI { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_NP> KALIP_IS_EMRI { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_DURUM_NP> KALIP_IS_EMRI_DURUM { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_IMALAT_DURUM> KALIP_IS_EMRI_IMALAT_DURUM { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_KALIP_DURUM> KALIP_IS_EMRI_KALIP_DURUM { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_KALIPHANE> KALIP_IS_EMRI_KALIPHANE { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_KALIPHANE_BARKOD> KALIP_IS_EMRI_KALIPHANE_BARKOD { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_KALITE_KONTROL> KALIP_IS_EMRI_KALITE_KONTROL { get; set; }
        public virtual DbSet<KALIP_IS_EMRI_ROTA> KALIP_IS_EMRI_ROTA { get; set; }
        public virtual DbSet<KALIP_OLUSTUR_FORM> KALIP_OLUSTUR_FORM { get; set; }
        public virtual DbSet<KALIP_TASARIM_FORM> KALIP_TASARIM_FORM { get; set; }
        public virtual DbSet<KALIP_TASARIM_POZ> KALIP_TASARIM_POZ { get; set; }
        public virtual DbSet<KALIPHANE_KART> KALIPHANE_KART { get; set; }
        public virtual DbSet<KALIPHANE_KART_OLUSTUR> KALIPHANE_KART_OLUSTUR { get; set; }
        public virtual DbSet<KALIPHANE_KART_ROTA> KALIPHANE_KART_ROTA { get; set; }
        public virtual DbSet<KAPASITE_PLAN> KAPASITE_PLAN { get; set; }
        public virtual DbSet<KULLANICI_AYARLAR> KULLANICI_AYARLAR { get; set; }
        public virtual DbSet<KULLANICI_KART_AYARLARI> KULLANICI_KART_AYARLARI { get; set; }
        public virtual DbSet<KULLANICI_LISTE_AYARLARI> KULLANICI_LISTE_AYARLARI { get; set; }
        public virtual DbSet<KULLANICI_SOHBET> KULLANICI_SOHBET { get; set; }
        public virtual DbSet<KULLANICI_SOHBET_MESAJ> KULLANICI_SOHBET_MESAJ { get; set; }
        public virtual DbSet<KULLANICI_YETKI> KULLANICI_YETKI { get; set; }
        public virtual DbSet<KURULUM_ALAN> KURULUM_ALAN { get; set; }
        public virtual DbSet<KURULUM_KART_GRUP_BAG> KURULUM_KART_GRUP_BAG { get; set; }
        public virtual DbSet<KURULUM_KART_GRUP_BAG_DETAY> KURULUM_KART_GRUP_BAG_DETAY { get; set; }
        public virtual DbSet<KURULUM_LISTE> KURULUM_LISTE { get; set; }
        public virtual DbSet<KURULUM_TABLO> KURULUM_TABLO { get; set; }
        public virtual DbSet<LISTE_AYARLARI> LISTE_AYARLARI { get; set; }
        public virtual DbSet<LISTE_AYARLARI_FONT> LISTE_AYARLARI_FONT { get; set; }
        public virtual DbSet<LOGLAR> LOGLAR { get; set; }
        public virtual DbSet<MALZEME_KART> MALZEME_KART { get; set; }
        public virtual DbSet<MESAJ_GOREV> MESAJ_GOREV { get; set; }
        public virtual DbSet<MESAJ_GOREV_ALICILAR> MESAJ_GOREV_ALICILAR { get; set; }
        public virtual DbSet<MONTAJ_FIS> MONTAJ_FIS { get; set; }
        public virtual DbSet<MONTAJ_PLAN> MONTAJ_PLAN { get; set; }
        public virtual DbSet<PDKS_CALISMA_DUZENLERI> PDKS_CALISMA_DUZENLERI { get; set; }
        public virtual DbSet<PDKS_CALISMA_DUZENLERI_ALT> PDKS_CALISMA_DUZENLERI_ALT { get; set; }
        public virtual DbSet<PDKS_CALISMA_DUZENLERI_HAFTALIK> PDKS_CALISMA_DUZENLERI_HAFTALIK { get; set; }
        public virtual DbSet<PDKS_CIHAZ> PDKS_CIHAZ { get; set; }
        public virtual DbSet<PDKS_CIHAZ_GONDER_AL_ZAMAN> PDKS_CIHAZ_GONDER_AL_ZAMAN { get; set; }
        public virtual DbSet<PDKS_IZIN_TANIMLARI> PDKS_IZIN_TANIMLARI { get; set; }
        public virtual DbSet<PDKS_PERSONEL_HAFTALIK_PLAN> PDKS_PERSONEL_HAFTALIK_PLAN { get; set; }
        public virtual DbSet<PDKS_PERSONEL_HAREKETLERI> PDKS_PERSONEL_HAREKETLERI { get; set; }
        public virtual DbSet<PDKS_PERSONEL_IZIN> PDKS_PERSONEL_IZIN { get; set; }
        public virtual DbSet<PDKS_PERSONEL_KAPI_HAREKETLERI> PDKS_PERSONEL_KAPI_HAREKETLERI { get; set; }
        public virtual DbSet<PDKS_PERSONEL_PUANTAJ> PDKS_PERSONEL_PUANTAJ { get; set; }
        public virtual DbSet<PDKS_PERSONEL_PUANTAJ_IZIN> PDKS_PERSONEL_PUANTAJ_IZIN { get; set; }
        public virtual DbSet<PDKS_PERSONEL_YEMEK> PDKS_PERSONEL_YEMEK { get; set; }
        public virtual DbSet<PDKS_PERSONEL_YEMEK_HAREKETLERI> PDKS_PERSONEL_YEMEK_HAREKETLERI { get; set; }
        public virtual DbSet<PDKS_TATIL_PLANLARI> PDKS_TATIL_PLANLARI { get; set; }
        public virtual DbSet<PDKS_ZIYARETCI_GIRIS_KART> PDKS_ZIYARETCI_GIRIS_KART { get; set; }
        public virtual DbSet<PDKS_ZIYARETCI_HAREKETLERI> PDKS_ZIYARETCI_HAREKETLERI { get; set; }
        public virtual DbSet<PDKS_ZIYARETCI_KART> PDKS_ZIYARETCI_KART { get; set; }
        public virtual DbSet<PERSONEL_ACIK_POZISYON> PERSONEL_ACIK_POZISYON { get; set; }
        public virtual DbSet<PERSONEL_EGITIM> PERSONEL_EGITIM { get; set; }
        public virtual DbSet<PERSONEL_EGITIM_PLAN> PERSONEL_EGITIM_PLAN { get; set; }
        public virtual DbSet<PERSONEL_GECICI_GOREV> PERSONEL_GECICI_GOREV { get; set; }
        public virtual DbSet<PERSONEL_IZIN> PERSONEL_IZIN { get; set; }
        public virtual DbSet<PERSONEL_IZIN_TANIMLARI> PERSONEL_IZIN_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_KART> PERSONEL_KART { get; set; }
        public virtual DbSet<PERSONEL_MASRAF> PERSONEL_MASRAF { get; set; }
        public virtual DbSet<PERSONEL_OZGECMIS> PERSONEL_OZGECMIS { get; set; }
        public virtual DbSet<PERSONEL_SEYAHAT> PERSONEL_SEYAHAT { get; set; }
        public virtual DbSet<PERSONEL_ZAMAN_CIZELGESI> PERSONEL_ZAMAN_CIZELGESI { get; set; }
        public virtual DbSet<PERSONEL_ZIMMET> PERSONEL_ZIMMET { get; set; }
        public virtual DbSet<POZ_KART_NP> POZ_KART { get; set; }
        public virtual DbSet<POZ_REVIZYON> POZ_REVIZYON { get; set; }
        public virtual DbSet<POZ_SIPARIS> POZ_SIPARIS { get; set; }
        public virtual DbSet<POZ_SIPARIS_FORM> POZ_SIPARIS_FORM { get; set; }
        public virtual DbSet<PROJE_BLOK_NP> PROJE_BLOK { get; set; }
        public virtual DbSet<PROJE_BLOK_CEPHE_NP> PROJE_BLOK_CEPHE { get; set; }
        public virtual DbSet<PROJE_BLOK_CEPHE_KAT_NP> PROJE_BLOK_CEPHE_KAT { get; set; }
        public virtual DbSet<PROJE_DOKUM_HEDEF> PROJE_DOKUM_HEDEF { get; set; }
        public virtual DbSet<PROJE_DOKUM_ROTA> PROJE_DOKUM_ROTA { get; set; }
        public virtual DbSet<PROJE_KART_NP> PROJE_KART { get; set; }
        public virtual DbSet<PROJE_MONTAJ_HEDEF> PROJE_MONTAJ_HEDEF { get; set; }
        public virtual DbSet<PROJE_SANTIYE> PROJE_SANTIYE { get; set; }
        public virtual DbSet<PROJE_SIPARIS_HEDEF> PROJE_SIPARIS_HEDEF { get; set; }
        public virtual DbSet<PROJE_TASERON> PROJE_TASERON { get; set; }
        public virtual DbSet<RAPOR_DIZAYN> RAPOR_DIZAYN { get; set; }
        public virtual DbSet<RESIM_YONETIM> RESIM_YONETIM { get; set; }
        public virtual DbSet<SEVK_FIRMA_KART> SEVK_FIRMA_KART { get; set; }
        public virtual DbSet<SEVK_FIRMA_YETKILI> SEVK_FIRMA_YETKILI { get; set; }
        public virtual DbSet<SEVK_FIS> SEVK_FIS { get; set; }
        public virtual DbSet<SEVK_POZ> SEVK_POZ { get; set; }
        public virtual DbSet<SEVK_SANDIKLAMA_FIS> SEVK_SANDIKLAMA_FIS { get; set; }
        public virtual DbSet<SEVK_TALEP_FIS_NP> SEVK_TALEP_FIS { get; set; }
        public virtual DbSet<SEVK_TALEP_POZ> SEVK_TALEP_POZ { get; set; }
        public virtual DbSet<SIPARIS_PLAN> SIPARIS_PLAN { get; set; }
        public virtual DbSet<UYGUNSUZLUK_FORM> UYGUNSUZLUK_FORM { get; set; }
        public virtual DbSet<UYGUNSUZLUK_RESIM> UYGUNSUZLUK_RESIM { get; set; }
        public virtual DbSet<UYGUNSUZLUK_TANIMLARI> UYGUNSUZLUK_TANIMLARI { get; set; }
        public virtual DbSet<KULLANICI_AKTIF> KULLANICI_AKTIF { get; set; }
        public virtual DbSet<MOBIL_LISTE_AYAR> MOBIL_LISTE_AYAR { get; set; }
    
        public virtual int GetNextSerialNumberForTable(string tableName, ObjectParameter formattedSerialNumber)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNextSerialNumberForTable", tableNameParameter, formattedSerialNumber);
        }
    
        public virtual int InsertInvoice(Nullable<int> invoiceData)
        {
            var invoiceDataParameter = invoiceData.HasValue ?
                new ObjectParameter("InvoiceData", invoiceData) :
                new ObjectParameter("InvoiceData", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertInvoice", invoiceDataParameter);
        }
    
        public virtual int indexanalizetolustur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("indexanalizetolustur");
        }
    
        public virtual int mailgonder(string profil, string body, string konu, string alici)
        {
            var profilParameter = profil != null ?
                new ObjectParameter("profil", profil) :
                new ObjectParameter("profil", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var konuParameter = konu != null ?
                new ObjectParameter("konu", konu) :
                new ObjectParameter("konu", typeof(string));
    
            var aliciParameter = alici != null ?
                new ObjectParameter("alici", alici) :
                new ObjectParameter("alici", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mailgonder", profilParameter, bodyParameter, konuParameter, aliciParameter);
        }
    
        public virtual int VerileriSil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerileriSil");
        }
    }
}
